
package com.cdoe.biz.model.transportation;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`CAPITAL_OUTLAY`")
public class CapitalOutlay implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="CAPITAL_OUTLAY_SEQ", sequenceName="CAPITAL_OUTLAY_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="CAPITAL_OUTLAY_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`RELATED_YEAR`")
	private Long relatedYear;

    public Long getRelatedYear () {
        return this.relatedYear;
    }

    public void setRelatedYear (Long relatedYear) {
        this.relatedYear = relatedYear;
    }

	@Column(name = "`BASE_YEAR`")
	private Long baseYear;

    public Long getBaseYear () {
        return this.baseYear;
    }

    public void setBaseYear (Long baseYear) {
        this.baseYear = baseYear;
    }

	@Column(name = "`CAPITAL_OUTLAY_TOTAL_FUNDING`")
	private Double capitalOutlayTotalFunding;

    public Double getCapitalOutlayTotalFunding () {
        return this.capitalOutlayTotalFunding;
    }

    public void setCapitalOutlayTotalFunding (Double capitalOutlayTotalFunding) {
        this.capitalOutlayTotalFunding = capitalOutlayTotalFunding;
    }

	@Column(name = "`OUTLAY_EXCLUSION`")
	private Double outlayExclusion;

    public Double getOutlayExclusion () {
        return this.outlayExclusion;
    }

    public void setOutlayExclusion (Double outlayExclusion) {
        this.outlayExclusion = outlayExclusion;
    }

	@Column(name = "`CONTRACTOR_MILES`")
	private Double contractorMiles;

    public Double getContractorMiles () {
        return this.contractorMiles;
    }

    public void setContractorMiles (Double contractorMiles) {
        this.contractorMiles = contractorMiles;
    }

	@Column(name = "`DEPRECIATION_PY`")
	private Double depreciationPy;

    public Double getDepreciationPy () {
        return this.depreciationPy;
    }

    public void setDepreciationPy (Double depreciationPy) {
        this.depreciationPy = depreciationPy;
    }

	@Column(name = "`REMAINING_AMT`")
	private Double remainingAmt;

    public Double getRemainingAmt () {
        return this.remainingAmt;
    }

    public void setRemainingAmt (Double remainingAmt) {
        this.remainingAmt = remainingAmt;
    }

	@Column(name = "`PREV_DEPRECIATED_AMT`")
	private Double prevDepreciatedAmt;

    public Double getPrevDepreciatedAmt () {
        return this.prevDepreciatedAmt;
    }

    public void setPrevDepreciatedAmt (Double prevDepreciatedAmt) {
        this.prevDepreciatedAmt = prevDepreciatedAmt;
    }

	@Column(name = "`DEPRECIATION_CYCLE`")
	private Double depreciationCycle;

    public Double getDepreciationCycle () {
        return this.depreciationCycle;
    }

    public void setDepreciationCycle (Double depreciationCycle) {
        this.depreciationCycle = depreciationCycle;
    }

	@Column(name = "`TOTAL_PURCHASE_PRICE`")
	private Double totalPurchasePrice;

    public Double getTotalPurchasePrice () {
        return this.totalPurchasePrice;
    }

    public void setTotalPurchasePrice (Double totalPurchasePrice) {
        this.totalPurchasePrice = totalPurchasePrice;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

    @Column(name="USER_ID")
    private String userId;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
}