
package com.cdoe.biz.model.transportation;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`TRANSPORTATION`")
public class Transportation implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="TRANSPORTATION_SEQ", sequenceName="TRANSPORTATION_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="TRANSPORTATION_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "`DATE_CHANGED`")
	private Date dateChanged;

    public Date getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (Date dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`ERRORS`")
	private String errors;

    public String getErrors () {
        return this.errors;
    }

    public void setErrors (String errors) {
        this.errors = errors;
    }

	@Column(name = "`PUPIL_TRAN`")
	private Long pupilTran;

    public Long getPupilTran () {
        return this.pupilTran;
    }

    public void setPupilTran (Long pupilTran) {
        this.pupilTran = pupilTran;
    }

	@Column(name = "`OPER_TRAN`")
	private Double operTran;

    public Double getOperTran () {
        return this.operTran;
    }

    public void setOperTran (Double operTran) {
        this.operTran = operTran;
    }

	@Column(name = "`IND_CONT`")
	private Double indCont;

    public Double getIndCont () {
        return this.indCont;
    }

    public void setIndCont (Double indCont) {
        this.indCont = indCont;
    }

	@Column(name = "`CAP_OUT_TRAN`")
	private Double capOutTran;

    public Double getCapOutTran () {
        return this.capOutTran;
    }

    public void setCapOutTran (Double capOutTran) {
        this.capOutTran = capOutTran;
    }

	@Column(name = "`MIG_MILES`")
	private Double migMiles;

    public Double getMigMiles () {
        return this.migMiles;
    }

    public void setMigMiles (Double migMiles) {
        this.migMiles = migMiles;
    }

	@Column(name = "`REG_D_MILES`")
	private Double regDMiles;

    public Double getRegDMiles () {
        return this.regDMiles;
    }

    public void setRegDMiles (Double regDMiles) {
        this.regDMiles = regDMiles;
    }

	@Column(name = "`SCHOOL_DAYS`")
	private Long schoolDays;

    public Long getSchoolDays () {
        return this.schoolDays;
    }

    public void setSchoolDays (Long schoolDays) {
        this.schoolDays = schoolDays;
    }

	@Column(name = "`REG_DAYS`")
	private Long regDays;

    public Long getRegDays () {
        return this.regDays;
    }

    public void setRegDays (Long regDays) {
        this.regDays = regDays;
    }

	@Column(name = "`BOARD_TRAN`")
	private Long boardTran;

    public Long getBoardTran () {
        return this.boardTran;
    }

    public void setBoardTran (Long boardTran) {
        this.boardTran = boardTran;
    }

	@Column(name = "`EX_REIM`")
	private Double exReim;

    public Double getExReim () {
        return this.exReim;
    }

    public void setExReim (Double exReim) {
        this.exReim = exReim;
    }

	@Column(name = "`DESEG_REIM`")
	private Double desegReim;

    public Double getDesegReim () {
        return this.desegReim;
    }

    public void setDesegReim (Double desegReim) {
        this.desegReim = desegReim;
    }

	@Column(name = "`REIM_TRAN`")
	private Double reimTran;

    public Double getReimTran () {
        return this.reimTran;
    }

    public void setReimTran (Double reimTran) {
        this.reimTran = reimTran;
    }

	@Column(name = "`REIM_TRAN_LY`")
	private Double reimTranLy;

    public Double getReimTranLy () {
        return this.reimTranLy;
    }

    public void setReimTranLy (Double reimTranLy) {
        this.reimTranLy = reimTranLy;
    }

	@Column(name = "`ADV_PAY_LY`")
	private Double advPayLy;

    public Double getAdvPayLy () {
        return this.advPayLy;
    }

    public void setAdvPayLy (Double advPayLy) {
        this.advPayLy = advPayLy;
    }

	@Column(name = "`REIM_ADV_PAY`")
	private Double reimAdvPay;

    public Double getReimAdvPay () {
        return this.reimAdvPay;
    }

    public void setReimAdvPay (Double reimAdvPay) {
        this.reimAdvPay = reimAdvPay;
    }

	@Column(name = "`ADV_PAY`")
	private Double advPay;

    public Double getAdvPay () {
        return this.advPay;
    }

    public void setAdvPay (Double advPay) {
        this.advPay = advPay;
    }

	@Column(name = "`ACT_MILES`")
	private Double actMiles;

    public Double getActMiles () {
        return this.actMiles;
    }

    public void setActMiles (Double actMiles) {
        this.actMiles = actMiles;
    }

	@Column(name = "`TOTAL_MILES`")
	private Double totalMiles;

    public Double getTotalMiles () {
        return this.totalMiles;
    }

    public void setTotalMiles (Double totalMiles) {
        this.totalMiles = totalMiles;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`CDE_COMMENTS`")
	private String cdeComments;

    public String getCdeComments () {
        return this.cdeComments;
    }

    public void setCdeComments (String cdeComments) {
        this.cdeComments = cdeComments;
    }

	@Column(name = "`FIRST_PAYMENT`")
	private Double firstPayment;

    public Double getFirstPayment () {
        return this.firstPayment;
    }

    public void setFirstPayment (Double firstPayment) {
        this.firstPayment = firstPayment;
    }

	@Column(name = "`SECOND_PAYMENT`")
	private Double secondPayment;

    public Double getSecondPayment () {
        return this.secondPayment;
    }

    public void setSecondPayment (Double secondPayment) {
        this.secondPayment = secondPayment;
    }

	@Column(name = "`DISTRICT_DISTRIBUTION`")
	private Double districtDistribution;

    public Double getDistrictDistribution () {
        return this.districtDistribution;
    }

    public void setDistrictDistribution (Double districtDistribution) {
        this.districtDistribution = districtDistribution;
    }

	@Column(name = "`COFRS_BATCH_NUMBER`")
	private Double cofrsBatchNumber;

    public Double getCofrsBatchNumber () {
        return this.cofrsBatchNumber;
    }

    public void setCofrsBatchNumber (Double cofrsBatchNumber) {
        this.cofrsBatchNumber = cofrsBatchNumber;
    }

	@Column(name = "`COFRS_DATE_PAID`")
	private Date cofrsDatePaid;

    public Date getCofrsDatePaid () {
        return this.cofrsDatePaid;
    }

    public void setCofrsDatePaid (Date cofrsDatePaid) {
        this.cofrsDatePaid = cofrsDatePaid;
    }

	@Column(name = "`NAME_PREPARER_CDE40`")
	private String namePreparerCde40;

    public String getNamePreparerCde40 () {
        return this.namePreparerCde40;
    }

    public void setNamePreparerCde40 (String namePreparerCde40) {
        this.namePreparerCde40 = namePreparerCde40;
    }

	@Column(name = "`PHONE_PREPARER_CDE40`")
	private String phonePreparerCde40;

    public String getPhonePreparerCde40 () {
        return this.phonePreparerCde40;
    }

    public void setPhonePreparerCde40 (String phonePreparerCde40) {
        this.phonePreparerCde40 = phonePreparerCde40;
    }

	@Column(name = "`EMAIL_PREPARER_CDE40`")
	private String emailPreparerCde40;

    public String getEmailPreparerCde40 () {
        return this.emailPreparerCde40;
    }

    public void setEmailPreparerCde40 (String emailPreparerCde40) {
        this.emailPreparerCde40 = emailPreparerCde40;
    }

	@Column(name = "`FEES_COLLECTED`")
	private Double feesCollected;

    public Double getFeesCollected () {
        return this.feesCollected;
    }

    public void setFeesCollected (Double feesCollected) {
        this.feesCollected = feesCollected;
    }

	@Column(name = "`OTHER_REVENUE`")
	private Double otherRevenue;

    public Double getOtherRevenue () {
        return this.otherRevenue;
    }

    public void setOtherRevenue (Double otherRevenue) {
        this.otherRevenue = otherRevenue;
    }

	@Column(name = "`NET_CURRENT_OPER_EXPEND`")
	private Double netCurrentOperExpend;

    public Double getNetCurrentOperExpend () {
        return this.netCurrentOperExpend;
    }

    public void setNetCurrentOperExpend (Double netCurrentOperExpend) {
        this.netCurrentOperExpend = netCurrentOperExpend;
    }

	@Column(name = "`TOTAL_REIM_MILEAGE`")
	private Double totalReimMileage;

    public Double getTotalReimMileage () {
        return this.totalReimMileage;
    }

    public void setTotalReimMileage (Double totalReimMileage) {
        this.totalReimMileage = totalReimMileage;
    }

	@Column(name = "`MILEAGE_ENTITLEMENT`")
	private Double mileageEntitlement;

    public Double getMileageEntitlement () {
        return this.mileageEntitlement;
    }

    public void setMileageEntitlement (Double mileageEntitlement) {
        this.mileageEntitlement = mileageEntitlement;
    }

	@Column(name = "`EX_COSTS`")
	private Double exCosts;

    public Double getExCosts () {
        return this.exCosts;
    }

    public void setExCosts (Double exCosts) {
        this.exCosts = exCosts;
    }

	@Column(name = "`MAX_REIM_ENTITLEMENT`")
	private Double maxReimEntitlement;

    public Double getMaxReimEntitlement () {
        return this.maxReimEntitlement;
    }

    public void setMaxReimEntitlement (Double maxReimEntitlement) {
        this.maxReimEntitlement = maxReimEntitlement;
    }

	@Column(name = "`REIM_ENTITLEMENT`")
	private Double reimEntitlement;

    public Double getReimEntitlement () {
        return this.reimEntitlement;
    }

    public void setReimEntitlement (Double reimEntitlement) {
        this.reimEntitlement = reimEntitlement;
    }

	@Column(name = "`TOTAL_REIM_ENTITLEMENT`")
	private Double totalReimEntitlement;

    public Double getTotalReimEntitlement () {
        return this.totalReimEntitlement;
    }

    public void setTotalReimEntitlement (Double totalReimEntitlement) {
        this.totalReimEntitlement = totalReimEntitlement;
    }

	@Column(name = "`FINAL_REIM_ENTITLEMENT`")
	private Double finalReimEntitlement;

    public Double getFinalReimEntitlement () {
        return this.finalReimEntitlement;
    }

    public void setFinalReimEntitlement (Double finalReimEntitlement) {
        this.finalReimEntitlement = finalReimEntitlement;
    }

	@Column(name = "`FINAL_REIM_PRORATED`")
	private Double finalReimProrated;

    public Double getFinalReimProrated () {
        return this.finalReimProrated;
    }

    public void setFinalReimProrated (Double finalReimProrated) {
        this.finalReimProrated = finalReimProrated;
    }
    
    @Column(name="USER_ID")
    private String userId;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}