
package com.cdoe.biz.model.equal;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`CROSSWALK_CSI`")
public class CrosswalkCSI implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="CSI_SEQ", sequenceName="CSI_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="CSI_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;
	@Column(name = "`SCHOOL_CODE`")
	private String schoolCode;
	@Column(name = "CDE_MEMBER")
	private Double cdeMember;
	@Column(name = "MEMBER")
	private Double member;
	@Column(name = "PARTTIME_H")
	private Double parttimeH;
	@Column(name = "PARTTIME_F")
	private Double parttimeF;
	@Column(name = "FTE_NOT_ELIG")
	private Double fteNotElig;
	@Column(name = "FTE_ELIG")
	private Double fteElig;
	@Column(name = "FUNDED_COUNT")
	private Double fundedCount;
	@Column(name = "GRADE_LEVEL")
	private String gradeLevel;
	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;
	@Column(name = "ASCENT_TOT")
	private Double ascentTot;
	@Column(name = "LUNCH_F")
	private Double lunchF;
	@Column(name = "CSI_ONLINE_CNT")
	private Double csiOnlineCnt;
	

	@Column(name = "CSI_ASCENT_CNT")
	private Double csiAscentCnt;
	@Column(name = "CSI_KIND_FTE_CNT")
	private Double csiKindFteCnt;
	@Column(name = "CSI_FL_1_8_CNT")
	private Double csiFl18Cnt;
	@Column(name = "CSI_FL_K_12_CNT")
	private Double csiFlK12Cnt;
	@Column(name = "CSI_K_12_FTE_CNT")
	private Double csiK12FteCnt;
	@Column(name = "CSI_MEM_1_8_CNT")
	private Double csiMem18Cnt;
	@Column(name = "CSI_MEM_K_12_CNT")
	private Double csiMK12Cnt;
	@Column(name = "PER_PUPIL_REVENUE")
	private Double csiPerPupilRevenueCnt;
	@Column(name = "CSI_CPP_CNT")
	private Double csiCppCnt;
	@Column(name = "CSI_SUPPLEMENTAL_K")
	private Double csiSupplementalK;
	
	
	
	
    public Double getAscentTot() {
		return ascentTot;
	}

	public void setAscentTot(Double ascentTot) {
		this.ascentTot = ascentTot;
	}

	public Double getLunchF() {
		return lunchF;
	}

	public void setLunchF(Double lunchF) {
		this.lunchF = lunchF;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	

	

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	
	
    public String getSchoolCode () {
        return this.schoolCode;
    }

    public void setSchoolCode (String schoolCode) {
        this.schoolCode = schoolCode;
    }
	
	

    public Double getCdeMember() {
		return cdeMember;
	}

	public void setCdeMember(Double cdeMember) {
		this.cdeMember = cdeMember;
	}

	public Double getMember() {
		return member;
	}

	public void setMember(Double member) {
		this.member = member;
	}

	public Double getParttimeH() {
		return parttimeH;
	}

	public void setParttimeH(Double parttimeH) {
		this.parttimeH = parttimeH;
	}

	public Double getParttimeF() {
		return parttimeF;
	}

	public void setParttimeF(Double parttimeF) {
		this.parttimeF = parttimeF;
	}

	public Double getFteNotElig() {
		return fteNotElig;
	}

	public void setFteNotElig(Double fteNotElig) {
		this.fteNotElig = fteNotElig;
	}

	public Double getFteElig() {
		return fteElig;
	}

	public void setFteElig(Double fteElig) {
		this.fteElig = fteElig;
	}

	public Double getFundedCount() {
		return fundedCount;
	}

	public void setFundedCount(Double fundedCount) {
		this.fundedCount = fundedCount;
	}



	public String getGradeLevel() {
		return gradeLevel;
	}

	public void setGradeLevel(String gradeLevel) {
		this.gradeLevel = gradeLevel;
	}
	
	public Double getCsiOnlineCnt() {
		return csiOnlineCnt;
	}

	public void setCsiOnlineCnt(Double csiOnlineCnt) {
		this.csiOnlineCnt = csiOnlineCnt;
	}

	public Double getCsiAscentCnt() {
		return csiAscentCnt;
	}

	public void setCsiAscentCnt(Double csiAscentCnt) {
		this.csiAscentCnt = csiAscentCnt;
	}

	public Double getCsiKindFteCnt() {
		return csiKindFteCnt;
	}

	public void setCsiKindFteCnt(Double csiKindFteCnt) {
		this.csiKindFteCnt = csiKindFteCnt;
	}

	public Double getCsiFl18Cnt() {
		return csiFl18Cnt;
	}

	public void setCsiFl18Cnt(Double csiFl18Cnt) {
		this.csiFl18Cnt = csiFl18Cnt;
	}

	public Double getCsiFlK12Cnt() {
		return csiFlK12Cnt;
	}

	public void setCsiFlK12Cnt(Double csiFlK12Cnt) {
		this.csiFlK12Cnt = csiFlK12Cnt;
	}

	public Double getCsiK12FteCnt() {
		return csiK12FteCnt;
	}

	public void setCsiK12FteCnt(Double csiK12FteCnt) {
		this.csiK12FteCnt = csiK12FteCnt;
	}

	public Double getCsiMem18Cnt() {
		return csiMem18Cnt;
	}

	public void setCsiMem18Cnt(Double csiMem18Cnt) {
		this.csiMem18Cnt = csiMem18Cnt;
	}

	public Double getCsiMK12Cnt() {
		return csiMK12Cnt;
	}

	public void setCsiMK12Cnt(Double csiMK12Cnt) {
		this.csiMK12Cnt = csiMK12Cnt;
	}

	public Double getCsiPerPupilRevenueCnt() {
		return csiPerPupilRevenueCnt;
	}

	public void setCsiPerPupilRevenueCnt(Double csiPerPupilRevenueCnt) {
		this.csiPerPupilRevenueCnt = csiPerPupilRevenueCnt;
	}

	public Double getCsiCppCnt() {
		return csiCppCnt;
	}

	public void setCsiCppCnt(Double csiCppCnt) {
		this.csiCppCnt = csiCppCnt;
	}

	public Double getCsiSupplementalK() {
		return csiSupplementalK;
	}

	public void setCsiSupplementalK(Double csiSupplementalK) {
		this.csiSupplementalK = csiSupplementalK;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

    @Column(name="USER_ID")
    private String userId;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
}