
package com.cdoe.biz.model.equal;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`FUNDED_COUNT`")
public class FundedCount implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`DATE_CHANGED`")
	private String dateChanged;

    public String getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (String dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`DISTNUM`")
	private String distnum;

    public String getDistnum () {
        return this.distnum;
    }

    public void setDistnum (String distnum) {
        this.distnum = distnum;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`MEMBER_PS`")
	private Long memberPs;

    public Long getMemberPs () {
        return this.memberPs;
    }

    public void setMemberPs (Long memberPs) {
        this.memberPs = memberPs;
    }

	@Column(name = "`PARTTIME_H_PS`")
	private Long parttimeHPs;

    public Long getParttimeHPs () {
        return this.parttimeHPs;
    }

    public void setParttimeHPs (Long parttimeHPs) {
        this.parttimeHPs = parttimeHPs;
    }

	@Column(name = "`PARTTIME_F_PS`")
	private Long parttimeFPs;

    public Long getParttimeFPs () {
        return this.parttimeFPs;
    }

    public void setParttimeFPs (Long parttimeFPs) {
        this.parttimeFPs = parttimeFPs;
    }

	@Column(name = "`OUT_OF_DIST_PS`")
	private Long outOfDistPs;

    public Long getOutOfDistPs () {
        return this.outOfDistPs;
    }

    public void setOutOfDistPs (Long outOfDistPs) {
        this.outOfDistPs = outOfDistPs;
    }

	@Column(name = "`SECND_SEM_H_PS`")
	private Long secndSemHPs;

    public Long getSecndSemHPs () {
        return this.secndSemHPs;
    }

    public void setSecndSemHPs (Long secndSemHPs) {
        this.secndSemHPs = secndSemHPs;
    }

	@Column(name = "`SECND_SEM_F_PS`")
	private Long secndSemFPs;

    public Long getSecndSemFPs () {
        return this.secndSemFPs;
    }

    public void setSecndSemFPs (Long secndSemFPs) {
        this.secndSemFPs = secndSemFPs;
    }

	@Column(name = "`NONRESIDENT_PS`")
	private Long nonresidentPs;

    public Long getNonresidentPs () {
        return this.nonresidentPs;
    }

    public void setNonresidentPs (Long nonresidentPs) {
        this.nonresidentPs = nonresidentPs;
    }

	@Column(name = "`RESIDENT_PS`")
	private Long residentPs;

    public Long getResidentPs () {
        return this.residentPs;
    }

    public void setResidentPs (Long residentPs) {
        this.residentPs = residentPs;
    }

	@Column(name = "`FUNDED_COUNT_PS`")
	private Long fundedCountPs;

    public Long getFundedCountPs () {
        return this.fundedCountPs;
    }

    public void setFundedCountPs (Long fundedCountPs) {
        this.fundedCountPs = fundedCountPs;
    }

	@Column(name = "`MEMBER_P`")
	private Long memberP;

    public Long getMemberP () {
        return this.memberP;
    }

    public void setMemberP (Long memberP) {
        this.memberP = memberP;
    }

	@Column(name = "`PARTTIME_H_P`")
	private Long parttimeHP;

    public Long getParttimeHP () {
        return this.parttimeHP;
    }

    public void setParttimeHP (Long parttimeHP) {
        this.parttimeHP = parttimeHP;
    }

	@Column(name = "`PARTTIME_F_P`")
	private Long parttimeFP;

    public Long getParttimeFP () {
        return this.parttimeFP;
    }

    public void setParttimeFP (Long parttimeFP) {
        this.parttimeFP = parttimeFP;
    }

	@Column(name = "`SECND_SEM_H_P`")
	private Long secndSemHP;

    public Long getSecndSemHP () {
        return this.secndSemHP;
    }

    public void setSecndSemHP (Long secndSemHP) {
        this.secndSemHP = secndSemHP;
    }

	@Column(name = "`OUT_OF_DIST_P`")
	private Long outOfDistP;

    public Long getOutOfDistP () {
        return this.outOfDistP;
    }

    public void setOutOfDistP (Long outOfDistP) {
        this.outOfDistP = outOfDistP;
    }

	@Column(name = "`NONRESIDENT_P`")
	private Long nonresidentP;

    public Long getNonresidentP () {
        return this.nonresidentP;
    }

    public void setNonresidentP (Long nonresidentP) {
        this.nonresidentP = nonresidentP;
    }

	@Column(name = "`RESIDENT_P`")
	private Long residentP;

    public Long getResidentP () {
        return this.residentP;
    }

    public void setResidentP (Long residentP) {
        this.residentP = residentP;
    }

	@Column(name = "`FUNDED_COUNT_P`")
	private Long fundedCountP;

    public Long getFundedCountP () {
        return this.fundedCountP;
    }

    public void setFundedCountP (Long fundedCountP) {
        this.fundedCountP = fundedCountP;
    }

	@Column(name = "`CDE_MEMBER_K`")
	private Long cdeMemberK;

    public Long getCdeMemberK () {
        return this.cdeMemberK;
    }

    public void setCdeMemberK (Long cdeMemberK) {
        this.cdeMemberK = cdeMemberK;
    }

	@Column(name = "`MEMBER_K`")
	private Long memberK;

    public Long getMemberK () {
        return this.memberK;
    }

    public void setMemberK (Long memberK) {
        this.memberK = memberK;
    }

	@Column(name = "`PARTTIME_H_K`")
	private Long parttimeHK;

    public Long getParttimeHK () {
        return this.parttimeHK;
    }

    public void setParttimeHK (Long parttimeHK) {
        this.parttimeHK = parttimeHK;
    }

	@Column(name = "`PARTTIME_F_K`")
	private Long parttimeFK;

    public Long getParttimeFK () {
        return this.parttimeFK;
    }

    public void setParttimeFK (Long parttimeFK) {
        this.parttimeFK = parttimeFK;
    }

	@Column(name = "`OUT_OF_DIST_K`")
	private Long outOfDistK;

    public Long getOutOfDistK () {
        return this.outOfDistK;
    }

    public void setOutOfDistK (Long outOfDistK) {
        this.outOfDistK = outOfDistK;
    }

	@Column(name = "`SECND_CH_D_H_K`")
	private Long secndChDHK;

    public Long getSecndChDHK () {
        return this.secndChDHK;
    }

    public void setSecndChDHK (Long secndChDHK) {
        this.secndChDHK = secndChDHK;
    }

	@Column(name = "`MEMBER_FULL_K`")
	private Long memberFullK;

    public Long getMemberFullK () {
        return this.memberFullK;
    }

    public void setMemberFullK (Long memberFullK) {
        this.memberFullK = memberFullK;
    }

	@Column(name = "`SECND_CH_B_H_K`")
	private Long secndChBHK;

    public Long getSecndChBHK () {
        return this.secndChBHK;
    }

    public void setSecndChBHK (Long secndChBHK) {
        this.secndChBHK = secndChBHK;
    }

	@Column(name = "`SECND_CH_B_F_K`")
	private Long secndChBFK;

    public Long getSecndChBFK () {
        return this.secndChBFK;
    }

    public void setSecndChBFK (Long secndChBFK) {
        this.secndChBFK = secndChBFK;
    }

	@Column(name = "`SECND_SEM_H_K`")
	private Long secndSemHK;

    public Long getSecndSemHK () {
        return this.secndSemHK;
    }

    public void setSecndSemHK (Long secndSemHK) {
        this.secndSemHK = secndSemHK;
    }

	@Column(name = "`SECND_SEM_F_K`")
	private Long secndSemFK;

    public Long getSecndSemFK () {
        return this.secndSemFK;
    }

    public void setSecndSemFK (Long secndSemFK) {
        this.secndSemFK = secndSemFK;
    }

	@Column(name = "`NONRESIDENT_K`")
	private Long nonresidentK;

    public Long getNonresidentK () {
        return this.nonresidentK;
    }

    public void setNonresidentK (Long nonresidentK) {
        this.nonresidentK = nonresidentK;
    }

	@Column(name = "`RESIDENT_K`")
	private Long residentK;

    public Long getResidentK () {
        return this.residentK;
    }

    public void setResidentK (Long residentK) {
        this.residentK = residentK;
    }

	@Column(name = "`FUNDED_COUNT_K`")
	private Long fundedCountK;

    public Long getFundedCountK () {
        return this.fundedCountK;
    }

    public void setFundedCountK (Long fundedCountK) {
        this.fundedCountK = fundedCountK;
    }

	@Column(name = "`CDE_MEMBER_1`")
	private Long cdeMember1;

    public Long getCdeMember1 () {
        return this.cdeMember1;
    }

    public void setCdeMember1 (Long cdeMember1) {
        this.cdeMember1 = cdeMember1;
    }

	@Column(name = "`MEMBER_1`")
	private Long member1;

    public Long getMember1 () {
        return this.member1;
    }

    public void setMember1 (Long member1) {
        this.member1 = member1;
    }

	@Column(name = "`PARTTIME_H_1`")
	private Long parttimeH1;

    public Long getParttimeH1 () {
        return this.parttimeH1;
    }

    public void setParttimeH1 (Long parttimeH1) {
        this.parttimeH1 = parttimeH1;
    }

	@Column(name = "`PARTTIME_F_1`")
	private Long parttimeF1;

    public Long getParttimeF1 () {
        return this.parttimeF1;
    }

    public void setParttimeF1 (Long parttimeF1) {
        this.parttimeF1 = parttimeF1;
    }

	@Column(name = "`SECND_CH_D_H_1`")
	private Long secndChDH1;

    public Long getSecndChDH1 () {
        return this.secndChDH1;
    }

    public void setSecndChDH1 (Long secndChDH1) {
        this.secndChDH1 = secndChDH1;
    }

	@Column(name = "`SECND_CH_D_F_1`")
	private Long secndChDF1;

    public Long getSecndChDF1 () {
        return this.secndChDF1;
    }

    public void setSecndChDF1 (Long secndChDF1) {
        this.secndChDF1 = secndChDF1;
    }

	@Column(name = "`SECND_CH_B_H_1`")
	private Long secndChBH1;

    public Long getSecndChBH1 () {
        return this.secndChBH1;
    }

    public void setSecndChBH1 (Long secndChBH1) {
        this.secndChBH1 = secndChBH1;
    }

	@Column(name = "`OUT_OF_DIST_1`")
	private Long outOfDist1;

    public Long getOutOfDist1 () {
        return this.outOfDist1;
    }

    public void setOutOfDist1 (Long outOfDist1) {
        this.outOfDist1 = outOfDist1;
    }

	@Column(name = "`NONRESIDENT_1`")
	private Long nonresident1;

    public Long getNonresident1 () {
        return this.nonresident1;
    }

    public void setNonresident1 (Long nonresident1) {
        this.nonresident1 = nonresident1;
    }

	@Column(name = "`RESIDENT_1`")
	private Long resident1;

    public Long getResident1 () {
        return this.resident1;
    }

    public void setResident1 (Long resident1) {
        this.resident1 = resident1;
    }

	@Column(name = "`FUNDED_COUNT_1`")
	private Long fundedCount1;

    public Long getFundedCount1 () {
        return this.fundedCount1;
    }

    public void setFundedCount1 (Long fundedCount1) {
        this.fundedCount1 = fundedCount1;
    }

	@Column(name = "`CDE_MEMBER_2`")
	private Long cdeMember2;

    public Long getCdeMember2 () {
        return this.cdeMember2;
    }

    public void setCdeMember2 (Long cdeMember2) {
        this.cdeMember2 = cdeMember2;
    }

	@Column(name = "`MEMBER_2`")
	private Long member2;

    public Long getMember2 () {
        return this.member2;
    }

    public void setMember2 (Long member2) {
        this.member2 = member2;
    }

	@Column(name = "`PARTTIME_H_2`")
	private Long parttimeH2;

    public Long getParttimeH2 () {
        return this.parttimeH2;
    }

    public void setParttimeH2 (Long parttimeH2) {
        this.parttimeH2 = parttimeH2;
    }

	@Column(name = "`PARTTIME_F_2`")
	private Long parttimeF2;

    public Long getParttimeF2 () {
        return this.parttimeF2;
    }

    public void setParttimeF2 (Long parttimeF2) {
        this.parttimeF2 = parttimeF2;
    }

	@Column(name = "`SECND_CH_D_H_2`")
	private Long secndChDH2;

    public Long getSecndChDH2 () {
        return this.secndChDH2;
    }

    public void setSecndChDH2 (Long secndChDH2) {
        this.secndChDH2 = secndChDH2;
    }

	@Column(name = "`SECND_CH_D_F_2`")
	private Long secndChDF2;

    public Long getSecndChDF2 () {
        return this.secndChDF2;
    }

    public void setSecndChDF2 (Long secndChDF2) {
        this.secndChDF2 = secndChDF2;
    }

	@Column(name = "`SECND_CH_B_H_2`")
	private Long secndChBH2;

    public Long getSecndChBH2 () {
        return this.secndChBH2;
    }

    public void setSecndChBH2 (Long secndChBH2) {
        this.secndChBH2 = secndChBH2;
    }

	@Column(name = "`OUT_OF_DIST_2`")
	private Long outOfDist2;

    public Long getOutOfDist2 () {
        return this.outOfDist2;
    }

    public void setOutOfDist2 (Long outOfDist2) {
        this.outOfDist2 = outOfDist2;
    }

	@Column(name = "`NONRESIDENT_2`")
	private Long nonresident2;

    public Long getNonresident2 () {
        return this.nonresident2;
    }

    public void setNonresident2 (Long nonresident2) {
        this.nonresident2 = nonresident2;
    }

	@Column(name = "`RESIDENT_2`")
	private Long resident2;

    public Long getResident2 () {
        return this.resident2;
    }

    public void setResident2 (Long resident2) {
        this.resident2 = resident2;
    }

	@Column(name = "`FUNDED_COUNT_2`")
	private Long fundedCount2;

    public Long getFundedCount2 () {
        return this.fundedCount2;
    }

    public void setFundedCount2 (Long fundedCount2) {
        this.fundedCount2 = fundedCount2;
    }

	@Column(name = "`CDE_MEMBER_3`")
	private Long cdeMember3;

    public Long getCdeMember3 () {
        return this.cdeMember3;
    }

    public void setCdeMember3 (Long cdeMember3) {
        this.cdeMember3 = cdeMember3;
    }

	@Column(name = "`MEMBER_3`")
	private Long member3;

    public Long getMember3 () {
        return this.member3;
    }

    public void setMember3 (Long member3) {
        this.member3 = member3;
    }

	@Column(name = "`PARTTIME_H_3`")
	private Long parttimeH3;

    public Long getParttimeH3 () {
        return this.parttimeH3;
    }

    public void setParttimeH3 (Long parttimeH3) {
        this.parttimeH3 = parttimeH3;
    }

	@Column(name = "`PARTTIME_F_3`")
	private Long parttimeF3;

    public Long getParttimeF3 () {
        return this.parttimeF3;
    }

    public void setParttimeF3 (Long parttimeF3) {
        this.parttimeF3 = parttimeF3;
    }

	@Column(name = "`SECND_CH_D_H_3`")
	private Long secndChDH3;

    public Long getSecndChDH3 () {
        return this.secndChDH3;
    }

    public void setSecndChDH3 (Long secndChDH3) {
        this.secndChDH3 = secndChDH3;
    }

	@Column(name = "`SECND_CH_D_F_3`")
	private Long secndChDF3;

    public Long getSecndChDF3 () {
        return this.secndChDF3;
    }

    public void setSecndChDF3 (Long secndChDF3) {
        this.secndChDF3 = secndChDF3;
    }

	@Column(name = "`SECND_CH_B_H_3`")
	private Long secndChBH3;

    public Long getSecndChBH3 () {
        return this.secndChBH3;
    }

    public void setSecndChBH3 (Long secndChBH3) {
        this.secndChBH3 = secndChBH3;
    }

	@Column(name = "`OUT_OF_DIST_3`")
	private Long outOfDist3;

    public Long getOutOfDist3 () {
        return this.outOfDist3;
    }

    public void setOutOfDist3 (Long outOfDist3) {
        this.outOfDist3 = outOfDist3;
    }

	@Column(name = "`NONRESIDENT_3`")
	private Long nonresident3;

    public Long getNonresident3 () {
        return this.nonresident3;
    }

    public void setNonresident3 (Long nonresident3) {
        this.nonresident3 = nonresident3;
    }

	@Column(name = "`RESIDENT_3`")
	private Long resident3;

    public Long getResident3 () {
        return this.resident3;
    }

    public void setResident3 (Long resident3) {
        this.resident3 = resident3;
    }

	@Column(name = "`FUNDED_COUNT_3`")
	private Long fundedCount3;

    public Long getFundedCount3 () {
        return this.fundedCount3;
    }

    public void setFundedCount3 (Long fundedCount3) {
        this.fundedCount3 = fundedCount3;
    }

	@Column(name = "`CDE_MEMBER_4`")
	private Long cdeMember4;

    public Long getCdeMember4 () {
        return this.cdeMember4;
    }

    public void setCdeMember4 (Long cdeMember4) {
        this.cdeMember4 = cdeMember4;
    }

	@Column(name = "`MEMBER_4`")
	private Long member4;

    public Long getMember4 () {
        return this.member4;
    }

    public void setMember4 (Long member4) {
        this.member4 = member4;
    }

	@Column(name = "`PARTTIME_H_4`")
	private Long parttimeH4;

    public Long getParttimeH4 () {
        return this.parttimeH4;
    }

    public void setParttimeH4 (Long parttimeH4) {
        this.parttimeH4 = parttimeH4;
    }

	@Column(name = "`PARTTIME_F_4`")
	private Long parttimeF4;

    public Long getParttimeF4 () {
        return this.parttimeF4;
    }

    public void setParttimeF4 (Long parttimeF4) {
        this.parttimeF4 = parttimeF4;
    }

	@Column(name = "`SECND_CH_D_H_4`")
	private Long secndChDH4;

    public Long getSecndChDH4 () {
        return this.secndChDH4;
    }

    public void setSecndChDH4 (Long secndChDH4) {
        this.secndChDH4 = secndChDH4;
    }

	@Column(name = "`SECND_CH_D_F_4`")
	private Long secndChDF4;

    public Long getSecndChDF4 () {
        return this.secndChDF4;
    }

    public void setSecndChDF4 (Long secndChDF4) {
        this.secndChDF4 = secndChDF4;
    }

	@Column(name = "`SECND_CH_B_H_4`")
	private Long secndChBH4;

    public Long getSecndChBH4 () {
        return this.secndChBH4;
    }

    public void setSecndChBH4 (Long secndChBH4) {
        this.secndChBH4 = secndChBH4;
    }

	@Column(name = "`OUT_OF_DIST_4`")
	private Long outOfDist4;

    public Long getOutOfDist4 () {
        return this.outOfDist4;
    }

    public void setOutOfDist4 (Long outOfDist4) {
        this.outOfDist4 = outOfDist4;
    }

	@Column(name = "`NONRESIDENT_4`")
	private Long nonresident4;

    public Long getNonresident4 () {
        return this.nonresident4;
    }

    public void setNonresident4 (Long nonresident4) {
        this.nonresident4 = nonresident4;
    }

	@Column(name = "`RESIDENT_4`")
	private Long resident4;

    public Long getResident4 () {
        return this.resident4;
    }

    public void setResident4 (Long resident4) {
        this.resident4 = resident4;
    }

	@Column(name = "`FUNDED_COUNT_4`")
	private Long fundedCount4;

    public Long getFundedCount4 () {
        return this.fundedCount4;
    }

    public void setFundedCount4 (Long fundedCount4) {
        this.fundedCount4 = fundedCount4;
    }

	@Column(name = "`CDE_MEMBER_5`")
	private Long cdeMember5;

    public Long getCdeMember5 () {
        return this.cdeMember5;
    }

    public void setCdeMember5 (Long cdeMember5) {
        this.cdeMember5 = cdeMember5;
    }

	@Column(name = "`MEMBER_5`")
	private Long member5;

    public Long getMember5 () {
        return this.member5;
    }

    public void setMember5 (Long member5) {
        this.member5 = member5;
    }

	@Column(name = "`PARTTIME_H_5`")
	private Long parttimeH5;

    public Long getParttimeH5 () {
        return this.parttimeH5;
    }

    public void setParttimeH5 (Long parttimeH5) {
        this.parttimeH5 = parttimeH5;
    }

	@Column(name = "`PARTTIME_F_5`")
	private Long parttimeF5;

    public Long getParttimeF5 () {
        return this.parttimeF5;
    }

    public void setParttimeF5 (Long parttimeF5) {
        this.parttimeF5 = parttimeF5;
    }

	@Column(name = "`SECND_CH_D_H_5`")
	private Long secndChDH5;

    public Long getSecndChDH5 () {
        return this.secndChDH5;
    }

    public void setSecndChDH5 (Long secndChDH5) {
        this.secndChDH5 = secndChDH5;
    }

	@Column(name = "`SECND_CH_D_F_5`")
	private Long secndChDF5;

    public Long getSecndChDF5 () {
        return this.secndChDF5;
    }

    public void setSecndChDF5 (Long secndChDF5) {
        this.secndChDF5 = secndChDF5;
    }

	@Column(name = "`SECND_CH_B_H_5`")
	private Long secndChBH5;

    public Long getSecndChBH5 () {
        return this.secndChBH5;
    }

    public void setSecndChBH5 (Long secndChBH5) {
        this.secndChBH5 = secndChBH5;
    }

	@Column(name = "`OUT_OF_DIST_5`")
	private Long outOfDist5;

    public Long getOutOfDist5 () {
        return this.outOfDist5;
    }

    public void setOutOfDist5 (Long outOfDist5) {
        this.outOfDist5 = outOfDist5;
    }

	@Column(name = "`NONRESIDENT_5`")
	private Long nonresident5;

    public Long getNonresident5 () {
        return this.nonresident5;
    }

    public void setNonresident5 (Long nonresident5) {
        this.nonresident5 = nonresident5;
    }

	@Column(name = "`RESIDENT_5`")
	private Long resident5;

    public Long getResident5 () {
        return this.resident5;
    }

    public void setResident5 (Long resident5) {
        this.resident5 = resident5;
    }

	@Column(name = "`FUNDED_COUNT_5`")
	private Long fundedCount5;

    public Long getFundedCount5 () {
        return this.fundedCount5;
    }

    public void setFundedCount5 (Long fundedCount5) {
        this.fundedCount5 = fundedCount5;
    }

	@Column(name = "`CDE_MEMBER_6`")
	private Long cdeMember6;

    public Long getCdeMember6 () {
        return this.cdeMember6;
    }

    public void setCdeMember6 (Long cdeMember6) {
        this.cdeMember6 = cdeMember6;
    }

	@Column(name = "`MEMBER_6`")
	private Long member6;

    public Long getMember6 () {
        return this.member6;
    }

    public void setMember6 (Long member6) {
        this.member6 = member6;
    }

	@Column(name = "`PARTTIME_H_6`")
	private Long parttimeH6;

    public Long getParttimeH6 () {
        return this.parttimeH6;
    }

    public void setParttimeH6 (Long parttimeH6) {
        this.parttimeH6 = parttimeH6;
    }

	@Column(name = "`PARTTIME_F_6`")
	private Long parttimeF6;

    public Long getParttimeF6 () {
        return this.parttimeF6;
    }

    public void setParttimeF6 (Long parttimeF6) {
        this.parttimeF6 = parttimeF6;
    }

	@Column(name = "`SECND_CH_D_H_6`")
	private Long secndChDH6;

    public Long getSecndChDH6 () {
        return this.secndChDH6;
    }

    public void setSecndChDH6 (Long secndChDH6) {
        this.secndChDH6 = secndChDH6;
    }

	@Column(name = "`SECND_CH_D_F_6`")
	private Long secndChDF6;

    public Long getSecndChDF6 () {
        return this.secndChDF6;
    }

    public void setSecndChDF6 (Long secndChDF6) {
        this.secndChDF6 = secndChDF6;
    }

	@Column(name = "`SECND_CH_B_H_6`")
	private Long secndChBH6;

    public Long getSecndChBH6 () {
        return this.secndChBH6;
    }

    public void setSecndChBH6 (Long secndChBH6) {
        this.secndChBH6 = secndChBH6;
    }

	@Column(name = "`OUT_OF_DIST_6`")
	private Long outOfDist6;

    public Long getOutOfDist6 () {
        return this.outOfDist6;
    }

    public void setOutOfDist6 (Long outOfDist6) {
        this.outOfDist6 = outOfDist6;
    }

	@Column(name = "`NONRESIDENT_6`")
	private Long nonresident6;

    public Long getNonresident6 () {
        return this.nonresident6;
    }

    public void setNonresident6 (Long nonresident6) {
        this.nonresident6 = nonresident6;
    }

	@Column(name = "`RESIDENT_6`")
	private Long resident6;

    public Long getResident6 () {
        return this.resident6;
    }

    public void setResident6 (Long resident6) {
        this.resident6 = resident6;
    }

	@Column(name = "`FUNDED_COUNT_6`")
	private Long fundedCount6;

    public Long getFundedCount6 () {
        return this.fundedCount6;
    }

    public void setFundedCount6 (Long fundedCount6) {
        this.fundedCount6 = fundedCount6;
    }

	@Column(name = "`CDE_MEMBER_7`")
	private Long cdeMember7;

    public Long getCdeMember7 () {
        return this.cdeMember7;
    }

    public void setCdeMember7 (Long cdeMember7) {
        this.cdeMember7 = cdeMember7;
    }

	@Column(name = "`MEMBER_7`")
	private Long member7;

    public Long getMember7 () {
        return this.member7;
    }

    public void setMember7 (Long member7) {
        this.member7 = member7;
    }

	@Column(name = "`PARTTIME_H_7`")
	private Long parttimeH7;

    public Long getParttimeH7 () {
        return this.parttimeH7;
    }

    public void setParttimeH7 (Long parttimeH7) {
        this.parttimeH7 = parttimeH7;
    }

	@Column(name = "`PARTTIME_F_7`")
	private Long parttimeF7;

    public Long getParttimeF7 () {
        return this.parttimeF7;
    }

    public void setParttimeF7 (Long parttimeF7) {
        this.parttimeF7 = parttimeF7;
    }

	@Column(name = "`SECND_CH_D_H_7`")
	private Long secndChDH7;

    public Long getSecndChDH7 () {
        return this.secndChDH7;
    }

    public void setSecndChDH7 (Long secndChDH7) {
        this.secndChDH7 = secndChDH7;
    }

	@Column(name = "`SECND_CH_D_F_7`")
	private Long secndChDF7;

    public Long getSecndChDF7 () {
        return this.secndChDF7;
    }

    public void setSecndChDF7 (Long secndChDF7) {
        this.secndChDF7 = secndChDF7;
    }

	@Column(name = "`SECND_CH_B_H_7`")
	private Long secndChBH7;

    public Long getSecndChBH7 () {
        return this.secndChBH7;
    }

    public void setSecndChBH7 (Long secndChBH7) {
        this.secndChBH7 = secndChBH7;
    }

	@Column(name = "`OUT_OF_DIST_7`")
	private Long outOfDist7;

    public Long getOutOfDist7 () {
        return this.outOfDist7;
    }

    public void setOutOfDist7 (Long outOfDist7) {
        this.outOfDist7 = outOfDist7;
    }

	@Column(name = "`NONRESIDENT_7`")
	private Long nonresident7;

    public Long getNonresident7 () {
        return this.nonresident7;
    }

    public void setNonresident7 (Long nonresident7) {
        this.nonresident7 = nonresident7;
    }

	@Column(name = "`RESIDENT_7`")
	private Long resident7;

    public Long getResident7 () {
        return this.resident7;
    }

    public void setResident7 (Long resident7) {
        this.resident7 = resident7;
    }

	@Column(name = "`FUNDED_COUNT_7`")
	private Long fundedCount7;

    public Long getFundedCount7 () {
        return this.fundedCount7;
    }

    public void setFundedCount7 (Long fundedCount7) {
        this.fundedCount7 = fundedCount7;
    }

	@Column(name = "`CDE_MEMBER_8`")
	private Long cdeMember8;

    public Long getCdeMember8 () {
        return this.cdeMember8;
    }

    public void setCdeMember8 (Long cdeMember8) {
        this.cdeMember8 = cdeMember8;
    }

	@Column(name = "`MEMBER_8`")
	private Long member8;

    public Long getMember8 () {
        return this.member8;
    }

    public void setMember8 (Long member8) {
        this.member8 = member8;
    }

	@Column(name = "`PARTTIME_H_8`")
	private Long parttimeH8;

    public Long getParttimeH8 () {
        return this.parttimeH8;
    }

    public void setParttimeH8 (Long parttimeH8) {
        this.parttimeH8 = parttimeH8;
    }

	@Column(name = "`PARTTIME_F_8`")
	private Long parttimeF8;

    public Long getParttimeF8 () {
        return this.parttimeF8;
    }

    public void setParttimeF8 (Long parttimeF8) {
        this.parttimeF8 = parttimeF8;
    }

	@Column(name = "`SECND_CH_D_H_8`")
	private Long secndChDH8;

    public Long getSecndChDH8 () {
        return this.secndChDH8;
    }

    public void setSecndChDH8 (Long secndChDH8) {
        this.secndChDH8 = secndChDH8;
    }

	@Column(name = "`SECND_CH_D_F_8`")
	private Long secndChDF8;

    public Long getSecndChDF8 () {
        return this.secndChDF8;
    }

    public void setSecndChDF8 (Long secndChDF8) {
        this.secndChDF8 = secndChDF8;
    }

	@Column(name = "`SECND_CH_B_H_8`")
	private Long secndChBH8;

    public Long getSecndChBH8 () {
        return this.secndChBH8;
    }

    public void setSecndChBH8 (Long secndChBH8) {
        this.secndChBH8 = secndChBH8;
    }

	@Column(name = "`OUT_OF_DIST_8`")
	private Long outOfDist8;

    public Long getOutOfDist8 () {
        return this.outOfDist8;
    }

    public void setOutOfDist8 (Long outOfDist8) {
        this.outOfDist8 = outOfDist8;
    }

	@Column(name = "`NONRESIDENT_8`")
	private Long nonresident8;

    public Long getNonresident8 () {
        return this.nonresident8;
    }

    public void setNonresident8 (Long nonresident8) {
        this.nonresident8 = nonresident8;
    }

	@Column(name = "`RESIDENT_8`")
	private Long resident8;

    public Long getResident8 () {
        return this.resident8;
    }

    public void setResident8 (Long resident8) {
        this.resident8 = resident8;
    }

	@Column(name = "`FUNDED_COUNT_8`")
	private Long fundedCount8;

    public Long getFundedCount8 () {
        return this.fundedCount8;
    }

    public void setFundedCount8 (Long fundedCount8) {
        this.fundedCount8 = fundedCount8;
    }

	@Column(name = "`CDE_MEMBER_9`")
	private Long cdeMember9;

    public Long getCdeMember9 () {
        return this.cdeMember9;
    }

    public void setCdeMember9 (Long cdeMember9) {
        this.cdeMember9 = cdeMember9;
    }

	@Column(name = "`MEMBER_9`")
	private Long member9;

    public Long getMember9 () {
        return this.member9;
    }

    public void setMember9 (Long member9) {
        this.member9 = member9;
    }

	@Column(name = "`PARTTIME_H_9`")
	private Long parttimeH9;

    public Long getParttimeH9 () {
        return this.parttimeH9;
    }

    public void setParttimeH9 (Long parttimeH9) {
        this.parttimeH9 = parttimeH9;
    }

	@Column(name = "`PARTTIME_F_9`")
	private Long parttimeF9;

    public Long getParttimeF9 () {
        return this.parttimeF9;
    }

    public void setParttimeF9 (Long parttimeF9) {
        this.parttimeF9 = parttimeF9;
    }

	@Column(name = "`SECND_CH_D_H_9`")
	private Long secndChDH9;

    public Long getSecndChDH9 () {
        return this.secndChDH9;
    }

    public void setSecndChDH9 (Long secndChDH9) {
        this.secndChDH9 = secndChDH9;
    }

	@Column(name = "`SECND_CH_D_F_9`")
	private Long secndChDF9;

    public Long getSecndChDF9 () {
        return this.secndChDF9;
    }

    public void setSecndChDF9 (Long secndChDF9) {
        this.secndChDF9 = secndChDF9;
    }

	@Column(name = "`SECND_CH_B_H_9`")
	private Long secndChBH9;

    public Long getSecndChBH9 () {
        return this.secndChBH9;
    }

    public void setSecndChBH9 (Long secndChBH9) {
        this.secndChBH9 = secndChBH9;
    }

	@Column(name = "`OUT_OF_DIST_9`")
	private Long outOfDist9;

    public Long getOutOfDist9 () {
        return this.outOfDist9;
    }

    public void setOutOfDist9 (Long outOfDist9) {
        this.outOfDist9 = outOfDist9;
    }

	@Column(name = "`NONRESIDENT_9`")
	private Long nonresident9;

    public Long getNonresident9 () {
        return this.nonresident9;
    }

    public void setNonresident9 (Long nonresident9) {
        this.nonresident9 = nonresident9;
    }

	@Column(name = "`RESIDENT_9`")
	private Long resident9;

    public Long getResident9 () {
        return this.resident9;
    }

    public void setResident9 (Long resident9) {
        this.resident9 = resident9;
    }

	@Column(name = "`FUNDED_COUNT_9`")
	private Long fundedCount9;

    public Long getFundedCount9 () {
        return this.fundedCount9;
    }

    public void setFundedCount9 (Long fundedCount9) {
        this.fundedCount9 = fundedCount9;
    }

	@Column(name = "`CDE_MEMBER_10`")
	private Long cdeMember10;

    public Long getCdeMember10 () {
        return this.cdeMember10;
    }

    public void setCdeMember10 (Long cdeMember10) {
        this.cdeMember10 = cdeMember10;
    }

	@Column(name = "`MEMBER_10`")
	private Long member10;

    public Long getMember10 () {
        return this.member10;
    }

    public void setMember10 (Long member10) {
        this.member10 = member10;
    }

	@Column(name = "`PARTTIME_H_10`")
	private Long parttimeH10;

    public Long getParttimeH10 () {
        return this.parttimeH10;
    }

    public void setParttimeH10 (Long parttimeH10) {
        this.parttimeH10 = parttimeH10;
    }

	@Column(name = "`PARTTIME_F_10`")
	private Long parttimeF10;

    public Long getParttimeF10 () {
        return this.parttimeF10;
    }

    public void setParttimeF10 (Long parttimeF10) {
        this.parttimeF10 = parttimeF10;
    }

	@Column(name = "`SECND_CH_D_H_10`")
	private Long secndChDH10;

    public Long getSecndChDH10 () {
        return this.secndChDH10;
    }

    public void setSecndChDH10 (Long secndChDH10) {
        this.secndChDH10 = secndChDH10;
    }

	@Column(name = "`SECND_CH_D_F_10`")
	private Long secndChDF10;

    public Long getSecndChDF10 () {
        return this.secndChDF10;
    }

    public void setSecndChDF10 (Long secndChDF10) {
        this.secndChDF10 = secndChDF10;
    }

	@Column(name = "`SECND_CH_B_H_10`")
	private Long secndChBH10;

    public Long getSecndChBH10 () {
        return this.secndChBH10;
    }

    public void setSecndChBH10 (Long secndChBH10) {
        this.secndChBH10 = secndChBH10;
    }

	@Column(name = "`OUT_OF_DIST_10`")
	private Long outOfDist10;

    public Long getOutOfDist10 () {
        return this.outOfDist10;
    }

    public void setOutOfDist10 (Long outOfDist10) {
        this.outOfDist10 = outOfDist10;
    }

	@Column(name = "`NONRESIDENT_10`")
	private Long nonresident10;

    public Long getNonresident10 () {
        return this.nonresident10;
    }

    public void setNonresident10 (Long nonresident10) {
        this.nonresident10 = nonresident10;
    }

	@Column(name = "`RESIDENT_10`")
	private Long resident10;

    public Long getResident10 () {
        return this.resident10;
    }

    public void setResident10 (Long resident10) {
        this.resident10 = resident10;
    }

	@Column(name = "`FUNDED_COUNT_10`")
	private Long fundedCount10;

    public Long getFundedCount10 () {
        return this.fundedCount10;
    }

    public void setFundedCount10 (Long fundedCount10) {
        this.fundedCount10 = fundedCount10;
    }

	@Column(name = "`CDE_MEMBER_11`")
	private Long cdeMember11;

    public Long getCdeMember11 () {
        return this.cdeMember11;
    }

    public void setCdeMember11 (Long cdeMember11) {
        this.cdeMember11 = cdeMember11;
    }

	@Column(name = "`MEMBER_11`")
	private Long member11;

    public Long getMember11 () {
        return this.member11;
    }

    public void setMember11 (Long member11) {
        this.member11 = member11;
    }

	@Column(name = "`PARTTIME_H_11`")
	private Long parttimeH11;

    public Long getParttimeH11 () {
        return this.parttimeH11;
    }

    public void setParttimeH11 (Long parttimeH11) {
        this.parttimeH11 = parttimeH11;
    }

	@Column(name = "`PARTTIME_F_11`")
	private Long parttimeF11;

    public Long getParttimeF11 () {
        return this.parttimeF11;
    }

    public void setParttimeF11 (Long parttimeF11) {
        this.parttimeF11 = parttimeF11;
    }

	@Column(name = "`SECND_CH_D_H_11`")
	private Long secndChDH11;

    public Long getSecndChDH11 () {
        return this.secndChDH11;
    }

    public void setSecndChDH11 (Long secndChDH11) {
        this.secndChDH11 = secndChDH11;
    }

	@Column(name = "`SECND_CH_D_F_11`")
	private Long secndChDF11;

    public Long getSecndChDF11 () {
        return this.secndChDF11;
    }

    public void setSecndChDF11 (Long secndChDF11) {
        this.secndChDF11 = secndChDF11;
    }

	@Column(name = "`SECND_CH_B_H_11`")
	private Long secndChBH11;

    public Long getSecndChBH11 () {
        return this.secndChBH11;
    }

    public void setSecndChBH11 (Long secndChBH11) {
        this.secndChBH11 = secndChBH11;
    }

	@Column(name = "`OUT_OF_DIST_11`")
	private Long outOfDist11;

    public Long getOutOfDist11 () {
        return this.outOfDist11;
    }

    public void setOutOfDist11 (Long outOfDist11) {
        this.outOfDist11 = outOfDist11;
    }

	@Column(name = "`NONRESIDENT_11`")
	private Long nonresident11;

    public Long getNonresident11 () {
        return this.nonresident11;
    }

    public void setNonresident11 (Long nonresident11) {
        this.nonresident11 = nonresident11;
    }

	@Column(name = "`RESIDENT_11`")
	private Long resident11;

    public Long getResident11 () {
        return this.resident11;
    }

    public void setResident11 (Long resident11) {
        this.resident11 = resident11;
    }

	@Column(name = "`FUNDED_COUNT_11`")
	private Long fundedCount11;

    public Long getFundedCount11 () {
        return this.fundedCount11;
    }

    public void setFundedCount11 (Long fundedCount11) {
        this.fundedCount11 = fundedCount11;
    }

	@Column(name = "`CDE_MEMBER_12`")
	private Long cdeMember12;

    public Long getCdeMember12 () {
        return this.cdeMember12;
    }

    public void setCdeMember12 (Long cdeMember12) {
        this.cdeMember12 = cdeMember12;
    }

	@Column(name = "`MEMBER_12`")
	private Long member12;

    public Long getMember12 () {
        return this.member12;
    }

    public void setMember12 (Long member12) {
        this.member12 = member12;
    }

	@Column(name = "`PARTTIME_H_12`")
	private Long parttimeH12;

    public Long getParttimeH12 () {
        return this.parttimeH12;
    }

    public void setParttimeH12 (Long parttimeH12) {
        this.parttimeH12 = parttimeH12;
    }

	@Column(name = "`PARTTIME_F_12`")
	private Long parttimeF12;

    public Long getParttimeF12 () {
        return this.parttimeF12;
    }

    public void setParttimeF12 (Long parttimeF12) {
        this.parttimeF12 = parttimeF12;
    }

	@Column(name = "`SECND_CH_D_H_12`")
	private Long secndChDH12;

    public Long getSecndChDH12 () {
        return this.secndChDH12;
    }

    public void setSecndChDH12 (Long secndChDH12) {
        this.secndChDH12 = secndChDH12;
    }

	@Column(name = "`SECND_CH_D_F_12`")
	private Long secndChDF12;

    public Long getSecndChDF12 () {
        return this.secndChDF12;
    }

    public void setSecndChDF12 (Long secndChDF12) {
        this.secndChDF12 = secndChDF12;
    }

	@Column(name = "`SECND_CH_B_H_12`")
	private Long secndChBH12;

    public Long getSecndChBH12 () {
        return this.secndChBH12;
    }

    public void setSecndChBH12 (Long secndChBH12) {
        this.secndChBH12 = secndChBH12;
    }

	@Column(name = "`OUT_OF_DIST_12`")
	private Long outOfDist12;

    public Long getOutOfDist12 () {
        return this.outOfDist12;
    }

    public void setOutOfDist12 (Long outOfDist12) {
        this.outOfDist12 = outOfDist12;
    }

	@Column(name = "`NONRESIDENT_12`")
	private Long nonresident12;

    public Long getNonresident12 () {
        return this.nonresident12;
    }

    public void setNonresident12 (Long nonresident12) {
        this.nonresident12 = nonresident12;
    }

	@Column(name = "`RESIDENT_12`")
	private Long resident12;

    public Long getResident12 () {
        return this.resident12;
    }

    public void setResident12 (Long resident12) {
        this.resident12 = resident12;
    }

	@Column(name = "`FUNDED_COUNT_12`")
	private Long fundedCount12;

    public Long getFundedCount12 () {
        return this.fundedCount12;
    }

    public void setFundedCount12 (Long fundedCount12) {
        this.fundedCount12 = fundedCount12;
    }

	@Column(name = "`CDE_MEMBER_SE`")
	private Long cdeMemberSe;

    public Long getCdeMemberSe () {
        return this.cdeMemberSe;
    }

    public void setCdeMemberSe (Long cdeMemberSe) {
        this.cdeMemberSe = cdeMemberSe;
    }

	@Column(name = "`MEMBER_SE`")
	private Long memberSe;

    public Long getMemberSe () {
        return this.memberSe;
    }

    public void setMemberSe (Long memberSe) {
        this.memberSe = memberSe;
    }

	@Column(name = "`PARTTIME_H_SE`")
	private Long parttimeHSe;

    public Long getParttimeHSe () {
        return this.parttimeHSe;
    }

    public void setParttimeHSe (Long parttimeHSe) {
        this.parttimeHSe = parttimeHSe;
    }

	@Column(name = "`PARTTIME_F_SE`")
	private Long parttimeFSe;

    public Long getParttimeFSe () {
        return this.parttimeFSe;
    }

    public void setParttimeFSe (Long parttimeFSe) {
        this.parttimeFSe = parttimeFSe;
    }

	@Column(name = "`SECND_CH_D_H_SE`")
	private Long secndChDHSe;

    public Long getSecndChDHSe () {
        return this.secndChDHSe;
    }

    public void setSecndChDHSe (Long secndChDHSe) {
        this.secndChDHSe = secndChDHSe;
    }

	@Column(name = "`SECND_CH_D_F_SE`")
	private Long secndChDFSe;

    public Long getSecndChDFSe () {
        return this.secndChDFSe;
    }

    public void setSecndChDFSe (Long secndChDFSe) {
        this.secndChDFSe = secndChDFSe;
    }

	@Column(name = "`SECND_CH_B_H_SE`")
	private Long secndChBHSe;

    public Long getSecndChBHSe () {
        return this.secndChBHSe;
    }

    public void setSecndChBHSe (Long secndChBHSe) {
        this.secndChBHSe = secndChBHSe;
    }

	@Column(name = "`SECND_CH_B_F_SE`")
	private Long secndChBFSe;

    public Long getSecndChBFSe () {
        return this.secndChBFSe;
    }

    public void setSecndChBFSe (Long secndChBFSe) {
        this.secndChBFSe = secndChBFSe;
    }

	@Column(name = "`NONRESIDENT_SE`")
	private Long nonresidentSe;

    public Long getNonresidentSe () {
        return this.nonresidentSe;
    }

    public void setNonresidentSe (Long nonresidentSe) {
        this.nonresidentSe = nonresidentSe;
    }

	@Column(name = "`RESIDENT_SE`")
	private Long residentSe;

    public Long getResidentSe () {
        return this.residentSe;
    }

    public void setResidentSe (Long residentSe) {
        this.residentSe = residentSe;
    }

	@Column(name = "`FUNDED_COUNT_SE`")
	private Long fundedCountSe;

    public Long getFundedCountSe () {
        return this.fundedCountSe;
    }

    public void setFundedCountSe (Long fundedCountSe) {
        this.fundedCountSe = fundedCountSe;
    }

	@Column(name = "`CDE_MEMBER_SS`")
	private Long cdeMemberSs;

    public Long getCdeMemberSs () {
        return this.cdeMemberSs;
    }

    public void setCdeMemberSs (Long cdeMemberSs) {
        this.cdeMemberSs = cdeMemberSs;
    }

	@Column(name = "`MEMBER_SS`")
	private Long memberSs;

    public Long getMemberSs () {
        return this.memberSs;
    }

    public void setMemberSs (Long memberSs) {
        this.memberSs = memberSs;
    }

	@Column(name = "`PARTTIME_H_SS`")
	private Long parttimeHSs;

    public Long getParttimeHSs () {
        return this.parttimeHSs;
    }

    public void setParttimeHSs (Long parttimeHSs) {
        this.parttimeHSs = parttimeHSs;
    }

	@Column(name = "`PARTTIME_F_SS`")
	private Long parttimeFSs;

    public Long getParttimeFSs () {
        return this.parttimeFSs;
    }

    public void setParttimeFSs (Long parttimeFSs) {
        this.parttimeFSs = parttimeFSs;
    }

	@Column(name = "`SECND_CH_D_H_SS`")
	private Long secndChDHSs;

    public Long getSecndChDHSs () {
        return this.secndChDHSs;
    }

    public void setSecndChDHSs (Long secndChDHSs) {
        this.secndChDHSs = secndChDHSs;
    }

	@Column(name = "`SECND_CH_D_F_SS`")
	private Long secndChDFSs;

    public Long getSecndChDFSs () {
        return this.secndChDFSs;
    }

    public void setSecndChDFSs (Long secndChDFSs) {
        this.secndChDFSs = secndChDFSs;
    }

	@Column(name = "`SECND_CH_B_H_SS`")
	private Long secndChBHSs;

    public Long getSecndChBHSs () {
        return this.secndChBHSs;
    }

    public void setSecndChBHSs (Long secndChBHSs) {
        this.secndChBHSs = secndChBHSs;
    }

	@Column(name = "`SECND_CH_B_F_SS`")
	private Long secndChBFSs;

    public Long getSecndChBFSs () {
        return this.secndChBFSs;
    }

    public void setSecndChBFSs (Long secndChBFSs) {
        this.secndChBFSs = secndChBFSs;
    }

	@Column(name = "`NONRESIDENT_SS`")
	private Long nonresidentSs;

    public Long getNonresidentSs () {
        return this.nonresidentSs;
    }

    public void setNonresidentSs (Long nonresidentSs) {
        this.nonresidentSs = nonresidentSs;
    }

	@Column(name = "`RESIDENT_SS`")
	private Long residentSs;

    public Long getResidentSs () {
        return this.residentSs;
    }

    public void setResidentSs (Long residentSs) {
        this.residentSs = residentSs;
    }

	@Column(name = "`FUNDED_COUNT_SS`")
	private Long fundedCountSs;

    public Long getFundedCountSs () {
        return this.fundedCountSs;
    }

    public void setFundedCountSs (Long fundedCountSs) {
        this.fundedCountSs = fundedCountSs;
    }

	@Column(name = "`CDE_MEMBER_UN`")
	private Long cdeMemberUn;

    public Long getCdeMemberUn () {
        return this.cdeMemberUn;
    }

    public void setCdeMemberUn (Long cdeMemberUn) {
        this.cdeMemberUn = cdeMemberUn;
    }

	@Column(name = "`MEMBER_UN`")
	private Long memberUn;

    public Long getMemberUn () {
        return this.memberUn;
    }

    public void setMemberUn (Long memberUn) {
        this.memberUn = memberUn;
    }

	@Column(name = "`PARTTIME_H_UN`")
	private Long parttimeHUn;

    public Long getParttimeHUn () {
        return this.parttimeHUn;
    }

    public void setParttimeHUn (Long parttimeHUn) {
        this.parttimeHUn = parttimeHUn;
    }

	@Column(name = "`PARTTIME_F_UN`")
	private Long parttimeFUn;

    public Long getParttimeFUn () {
        return this.parttimeFUn;
    }

    public void setParttimeFUn (Long parttimeFUn) {
        this.parttimeFUn = parttimeFUn;
    }

	@Column(name = "`OUT_OF_DIST_UN`")
	private Long outOfDistUn;

    public Long getOutOfDistUn () {
        return this.outOfDistUn;
    }

    public void setOutOfDistUn (Long outOfDistUn) {
        this.outOfDistUn = outOfDistUn;
    }

	@Column(name = "`SECND_CH_D_H_UN`")
	private Long secndChDHUn;

    public Long getSecndChDHUn () {
        return this.secndChDHUn;
    }

    public void setSecndChDHUn (Long secndChDHUn) {
        this.secndChDHUn = secndChDHUn;
    }

	@Column(name = "`SECND_CH_D_F_UN`")
	private Long secndChDFUn;

    public Long getSecndChDFUn () {
        return this.secndChDFUn;
    }

    public void setSecndChDFUn (Long secndChDFUn) {
        this.secndChDFUn = secndChDFUn;
    }

	@Column(name = "`SECND_CH_B_H_UN`")
	private Long secndChBHUn;

    public Long getSecndChBHUn () {
        return this.secndChBHUn;
    }

    public void setSecndChBHUn (Long secndChBHUn) {
        this.secndChBHUn = secndChBHUn;
    }

	@Column(name = "`SECND_CH_B_F_UN`")
	private Long secndChBFUn;

    public Long getSecndChBFUn () {
        return this.secndChBFUn;
    }

    public void setSecndChBFUn (Long secndChBFUn) {
        this.secndChBFUn = secndChBFUn;
    }

	@Column(name = "`NONRESIDENT_UN`")
	private Long nonresidentUn;

    public Long getNonresidentUn () {
        return this.nonresidentUn;
    }

    public void setNonresidentUn (Long nonresidentUn) {
        this.nonresidentUn = nonresidentUn;
    }

	@Column(name = "`RESIDENT_UN`")
	private Long residentUn;

    public Long getResidentUn () {
        return this.residentUn;
    }

    public void setResidentUn (Long residentUn) {
        this.residentUn = residentUn;
    }

	@Column(name = "`FUNDED_COUNT_UN`")
	private Long fundedCountUn;

    public Long getFundedCountUn () {
        return this.fundedCountUn;
    }

    public void setFundedCountUn (Long fundedCountUn) {
        this.fundedCountUn = fundedCountUn;
    }

	@Column(name = "`CDE_MEMBER`")
	private Long cdeMember;

    public Long getCdeMember () {
        return this.cdeMember;
    }

    public void setCdeMember (Long cdeMember) {
        this.cdeMember = cdeMember;
    }

	@Column(name = "`MEMBER`")
	private Long member;

    public Long getMember () {
        return this.member;
    }

    public void setMember (Long member) {
        this.member = member;
    }

	@Column(name = "`PARTTIME_H`")
	private Long parttimeH;

    public Long getParttimeH () {
        return this.parttimeH;
    }

    public void setParttimeH (Long parttimeH) {
        this.parttimeH = parttimeH;
    }

	@Column(name = "`PARTTIME_F`")
	private Long parttimeF;

    public Long getParttimeF () {
        return this.parttimeF;
    }

    public void setParttimeF (Long parttimeF) {
        this.parttimeF = parttimeF;
    }

	@Column(name = "`OUT_OF_DIST`")
	private Long outOfDist;

    public Long getOutOfDist () {
        return this.outOfDist;
    }

    public void setOutOfDist (Long outOfDist) {
        this.outOfDist = outOfDist;
    }

	@Column(name = "`SECND_CH_D_H`")
	private Long secndChDH;

    public Long getSecndChDH () {
        return this.secndChDH;
    }

    public void setSecndChDH (Long secndChDH) {
        this.secndChDH = secndChDH;
    }

	@Column(name = "`SECND_CH_D_F`")
	private Long secndChDF;

    public Long getSecndChDF () {
        return this.secndChDF;
    }

    public void setSecndChDF (Long secndChDF) {
        this.secndChDF = secndChDF;
    }

	@Column(name = "`SECND_CH_B_H`")
	private Long secndChBH;

    public Long getSecndChBH () {
        return this.secndChBH;
    }

    public void setSecndChBH (Long secndChBH) {
        this.secndChBH = secndChBH;
    }

	@Column(name = "`SECND_CH_B_F`")
	private Long secndChBF;

    public Long getSecndChBF () {
        return this.secndChBF;
    }

    public void setSecndChBF (Long secndChBF) {
        this.secndChBF = secndChBF;
    }

	@Column(name = "`SECND_SEM_H`")
	private Long secndSemH;

    public Long getSecndSemH () {
        return this.secndSemH;
    }

    public void setSecndSemH (Long secndSemH) {
        this.secndSemH = secndSemH;
    }

	@Column(name = "`SECND_SEM_F`")
	private Long secndSemF;

    public Long getSecndSemF () {
        return this.secndSemF;
    }

    public void setSecndSemF (Long secndSemF) {
        this.secndSemF = secndSemF;
    }

	@Column(name = "`NONRESIDENT`")
	private Long nonresident;

    public Long getNonresident () {
        return this.nonresident;
    }

    public void setNonresident (Long nonresident) {
        this.nonresident = nonresident;
    }

	@Column(name = "`RESIDENT`")
	private Long resident;

    public Long getResident () {
        return this.resident;
    }

    public void setResident (Long resident) {
        this.resident = resident;
    }

	@Column(name = "`FUNDED_COUNT`")
	private Long fundedCount;

    public Long getFundedCount () {
        return this.fundedCount;
    }

    public void setFundedCount (Long fundedCount) {
        this.fundedCount = fundedCount;
    }

	@Column(name = "`ASCENT`")
	private Long ascent;

    public Long getAscent () {
        return this.ascent;
    }

    public void setAscent (Long ascent) {
        this.ascent = ascent;
    }

}