
package com.cdoe.biz.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "Audit_Repayment")
public class AuditRepaymentAdjustment implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_REPAYMENT_SEQ", sequenceName="AUDIT_REPAYMENT_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_REPAYMENT_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "DISTRICT_NUMBER")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "BEGIN_FISCAL_YEAR")
	private String beginFiscalYear;

    public String getBeginFiscalYear () {
        return this.beginFiscalYear;
    }

    public void setBeginFiscalYear (String beginFiscalYear) {
        this.beginFiscalYear = beginFiscalYear;
    }

	@Column(name = "END_FISCAL_YEAR")
	private String endFiscalYear;

    public String getEndFiscalYear () {
        return this.endFiscalYear;
    }

    public void setEndFiscalYear (String endFiscalYear) {
        this.endFiscalYear = endFiscalYear;
    }

	@Column(name = "BEGIN_FISCAL_MONTH")
	private String beginFiscalMonth;

    public String getBeginFiscalMonth () {
        return this.beginFiscalMonth;
    }

    public void setBeginFiscalMonth (String beginFiscalMonth) {
        this.beginFiscalMonth = beginFiscalMonth;
    }

	@Column(name = "END_FISCAL_MONTH")
	private String endFiscalMonth;

    public String getEndFiscalMonth () {
        return this.endFiscalMonth;
    }

    public void setEndFiscalMonth (String endFiscalMonth) {
        this.endFiscalMonth = endFiscalMonth;
    }

	@Column(name = "FREQUENCY")
	private String frequency;

    public String getFrequency () {
        return this.frequency;
    }

    public void setFrequency (String frequency) {
        this.frequency = frequency;
    }

	@Column(name = "PAYMENT_AMOUNT")
	private Double amount;

    public Double getAmount () {
        return this.amount;
    }

    public void setAmount (Double amount) {
        this.amount = amount;
    }

    @Column(name="USER_ID")
    private String userId;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
}