
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDIT_CSI`")
public class AuditCsi implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_CSI_SEQ", sequenceName="AUDIT_CSI_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_CSI_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`AUDIT_ID`")
	private Integer auditId;

    public Integer getAuditId () {
        return this.auditId;
    }

    public void setAuditId (Integer auditId) {
        this.auditId = auditId;
    }

	@Column(name = "`UPDATE_TIMESTAMP`")
	private Date updateTimestamp;

    public Date getUpdateTimestamp () {
        return this.updateTimestamp;
    }

    public void setUpdateTimestamp (Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

	@Column(name = "`USER_ID`")
	private String userId;

    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

	@Column(name = "`CSI_ASCENT_CNT`")
	private Double csiAscentCnt;

    public Double getCsiAscentCnt () {
        return this.csiAscentCnt;
    }

    public void setCsiAscentCnt (Double csiAscentCnt) {
        this.csiAscentCnt = csiAscentCnt;
    }

	@Column(name = "`PER_PUPIL_REVENUE`")
	private Double perPupilRevenue;

    public Double getPerPupilRevenue () {
        return this.perPupilRevenue;
    }

    public void setPerPupilRevenue (Double perPupilRevenue) {
        this.perPupilRevenue = perPupilRevenue;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`CSI_KIND_FTE_CNT`")
	private Double csiKindFteCnt;

    public Double getCsiKindFteCnt () {
        return this.csiKindFteCnt;
    }

    public void setCsiKindFteCnt (Double csiKindFteCnt) {
        this.csiKindFteCnt = csiKindFteCnt;
    }

	@Column(name = "`CSI_CPP_CNT`")
	private Double csiCppCnt;

    public Double getCsiCppCnt () {
        return this.csiCppCnt;
    }

    public void setCsiCppCnt (Double csiCppCnt) {
        this.csiCppCnt = csiCppCnt;
    }

	@Column(name = "`CSI_MEM_K_12_CNT`")
	private Double csiMemK12Cnt;

    public Double getCsiMemK12Cnt () {
        return this.csiMemK12Cnt;
    }

    public void setCsiMemK12Cnt (Double csiMemK12Cnt) {
        this.csiMemK12Cnt = csiMemK12Cnt;
    }

	@Column(name = "`CSI_MEM_1_8_CNT`")
	private Double csiMem18Cnt;

    public Double getCsiMem18Cnt () {
        return this.csiMem18Cnt;
    }

    public void setCsiMem18Cnt (Double csiMem18Cnt) {
        this.csiMem18Cnt = csiMem18Cnt;
    }

	@Column(name = "`CSI_FL_K_12_CNT`")
	private Double csiFlK12Cnt;

    public Double getCsiFlK12Cnt () {
        return this.csiFlK12Cnt;
    }

    public void setCsiFlK12Cnt (Double csiFlK12Cnt) {
        this.csiFlK12Cnt = csiFlK12Cnt;
    }

	@Column(name = "`CSI_ONLINE_CNT`")
	private Double csiOnlineCnt;

    public Double getCsiOnlineCnt () {
        return this.csiOnlineCnt;
    }

    public void setCsiOnlineCnt (Double csiOnlineCnt) {
        this.csiOnlineCnt = csiOnlineCnt;
    }

	@Column(name = "`CSI_FL_1_8_CNT`")
	private Double csiFl18Cnt;

    public Double getCsiFl18Cnt () {
        return this.csiFl18Cnt;
    }

    public void setCsiFl18Cnt (Double csiFl18Cnt) {
        this.csiFl18Cnt = csiFl18Cnt;
    }

	@Column(name = "`CSI_SUPPLEMENTAL_K`")
	private Double csiSupplementalK;

    public Double getCsiSupplementalK () {
        return this.csiSupplementalK;
    }

    public void setCsiSupplementalK (Double csiSupplementalK) {
        this.csiSupplementalK = csiSupplementalK;
    }

	@Column(name = "`CSI_K_12_FTE_CNT`")
	private Double csiK12FteCnt;

    public Double getCsiK12FteCnt () {
        return this.csiK12FteCnt;
    }

    public void setCsiK12FteCnt (Double csiK12FteCnt) {
        this.csiK12FteCnt = csiK12FteCnt;
    }

	@Column(name = "`CSI_SCHOOL_NUMBER`")
	private String csiSchoolNumber;

    public String getCsiSchoolNumber () {
        return this.csiSchoolNumber;
    }

    public void setCsiSchoolNumber (String csiSchoolNumber) {
        this.csiSchoolNumber = csiSchoolNumber;
    }

	@Column(name = "`DATE_CHANGED`")
	private Date dateChanged;

    public Date getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (Date dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

}