
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDIT_EQUAL`")
public class AuditEqual implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_EQUAL_SEQ", sequenceName="AUDIT_EQUAL_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_EQUAL_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`CAT_SPED_DISABILITIES`")
	private Double catSpedDisabilities;

    public Double getCatSpedDisabilities () {
        return this.catSpedDisabilities;
    }

    public void setCatSpedDisabilities (Double catSpedDisabilities) {
        this.catSpedDisabilities = catSpedDisabilities;
    }

	@Column(name = "`CAT_ELPA`")
	private Double catElpa;

    public Double getCatElpa () {
        return this.catElpa;
    }

    public void setCatElpa (Double catElpa) {
        this.catElpa = catElpa;
    }

	@Column(name = "`CAT_VOCED`")
	private Double catVoced;

    public Double getCatVoced () {
        return this.catVoced;
    }

    public void setCatVoced (Double catVoced) {
        this.catVoced = catVoced;
    }

	@Column(name = "`CAT_TRANSPORTATION`")
	private Double catTransportation;

    public Double getCatTransportation () {
        return this.catTransportation;
    }

    public void setCatTransportation (Double catTransportation) {
        this.catTransportation = catTransportation;
    }

	@Column(name = "`ASSESSED_VAL`")
	private Double assessedVal;

    public Double getAssessedVal () {
        return this.assessedVal;
    }

    public void setAssessedVal (Double assessedVal) {
        this.assessedVal = assessedVal;
    }

	@Column(name = "`FUNDED_PUPIL_COUNT`")
	private Long fundedPupilCount;

    public Long getFundedPupilCount () {
        return this.fundedPupilCount;
    }

    public void setFundedPupilCount (Long fundedPupilCount) {
        this.fundedPupilCount = fundedPupilCount;
    }

	@Column(name = "`SPECED_PK`")
	private Double specedPk;

    public Double getSpecedPk () {
        return this.specedPk;
    }

    public void setSpecedPk (Double specedPk) {
        this.specedPk = specedPk;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`DATE_CHANGED`")
	private String dateChanged;

    public String getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (String dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "`MONTH_PAYMENT`")
	private Double monthPayment;

    public Double getMonthPayment () {
        return this.monthPayment;
    }

    public void setMonthPayment (Double monthPayment) {
        this.monthPayment = monthPayment;
    }

	@Column(name = "`YTD_ENTITLE`")
	private Double ytdEntitle;

    public Double getYtdEntitle () {
        return this.ytdEntitle;
    }

    public void setYtdEntitle (Double ytdEntitle) {
        this.ytdEntitle = ytdEntitle;
    }

	@Column(name = "`MONTH_ENTITLE`")
	private Double monthEntitle;

    public Double getMonthEntitle () {
        return this.monthEntitle;
    }

    public void setMonthEntitle (Double monthEntitle) {
        this.monthEntitle = monthEntitle;
    }

	@Column(name = "`MILL_LEVY_ADJ`")
	private Double millLevyAdj;

    public Double getMillLevyAdj () {
        return this.millLevyAdj;
    }

    public void setMillLevyAdj (Double millLevyAdj) {
        this.millLevyAdj = millLevyAdj;
    }

	@Column(name = "`CERT_TOTAL_PROGRAM_MILL_LEVY`")
	private Double certTotalProgramMillLevy;

    public Double getCertTotalProgramMillLevy () {
        return this.certTotalProgramMillLevy;
    }

    public void setCertTotalProgramMillLevy (Double certTotalProgramMillLevy) {
        this.certTotalProgramMillLevy = certTotalProgramMillLevy;
    }

	@Column(name = "`STATE_EQUAL`")
	private Double stateEqualOwner;

    public Double getStateEqualOwner () {
        return this.stateEqualOwner;
    }

    public void setStateEqualOwner (Double stateEqualOwner) {
        this.stateEqualOwner = stateEqualOwner;
    }

	@Column(name = "`PROPERTY_TAX`")
	private Double propertyTax;

    public Double getPropertyTax () {
        return this.propertyTax;
    }

    public void setPropertyTax (Double propertyTax) {
        this.propertyTax = propertyTax;
    }

	@Column(name = "`CALC_TOTAL_PROGRAM_MILL_LEVY`")
	private Double calcTotalProgramMillLevy;

    public Double getCalcTotalProgramMillLevy () {
        return this.calcTotalProgramMillLevy;
    }

    public void setCalcTotalProgramMillLevy (Double calcTotalProgramMillLevy) {
        this.calcTotalProgramMillLevy = calcTotalProgramMillLevy;
    }

	@Column(name = "`SOT_GROSS`")
	private Double sotGross;

    public Double getSotGross () {
        return this.sotGross;
    }

    public void setSotGross (Double sotGross) {
        this.sotGross = sotGross;
    }

	@Column(name = "`GRAND_TOTAL_PROGRAM`")
	private Double grandTotalProgram;

    public Double getGrandTotalProgram () {
        return this.grandTotalProgram;
    }

    public void setGrandTotalProgram (Double grandTotalProgram) {
        this.grandTotalProgram = grandTotalProgram;
    }

	@Column(name = "`TOTAL_PROGRAM_AT_RISK`")
	private Double totalProgramAtRisk;

    public Double getTotalProgramAtRisk () {
        return this.totalProgramAtRisk;
    }

    public void setTotalProgramAtRisk (Double totalProgramAtRisk) {
        this.totalProgramAtRisk = totalProgramAtRisk;
    }

	@Column(name = "`MEMBER_1_8`")
	private Double member18;

    public Double getMember18 () {
        return this.member18;
    }

    public void setMember18 (Double member18) {
        this.member18 = member18;
    }

	@Column(name = "`FREE_LUNCH_K_12`")
	private Double freeLunchK12;

    public Double getFreeLunchK12 () {
        return this.freeLunchK12;
    }

    public void setFreeLunchK12 (Double freeLunchK12) {
        this.freeLunchK12 = freeLunchK12;
    }

	@Column(name = "`FREE_LUNCH_1_8`")
	private Double freeLunch18;

    public Double getFreeLunch18 () {
        return this.freeLunch18;
    }

    public void setFreeLunch18 (Double freeLunch18) {
        this.freeLunch18 = freeLunch18;
    }

	@Column(name = "`COST_OF_LIVING_FACTOR`")
	private Double costOfLivingFactor;

    public Double getCostOfLivingFactor () {
        return this.costOfLivingFactor;
    }

    public void setCostOfLivingFactor (Double costOfLivingFactor) {
        this.costOfLivingFactor = costOfLivingFactor;
    }

	@Column(name = "`PERSONNEL_COST_FACTOR`")
	private Double personnelCostFactor;

    public Double getPersonnelCostFactor () {
        return this.personnelCostFactor;
    }

    public void setPersonnelCostFactor (Double personnelCostFactor) {
        this.personnelCostFactor = personnelCostFactor;
    }

	@Column(name = "`FORMULA_TP_WO_AT_RISK`")
	private Double formulaTpWoAtRisk;

    public Double getFormulaTpWoAtRisk () {
        return this.formulaTpWoAtRisk;
    }

    public void setFormulaTpWoAtRisk (Double formulaTpWoAtRisk) {
        this.formulaTpWoAtRisk = formulaTpWoAtRisk;
    }

	@Column(name = "`SIZE_FACTOR`")
	private Double sizeFactor;

    public Double getSizeFactor () {
        return this.sizeFactor;
    }

    public void setSizeFactor (Double sizeFactor) {
        this.sizeFactor = sizeFactor;
    }

	@Column(name = "`CAT_SPED_GIFTED_TALENTED`")
	private Double catSpedGiftedTalented;

    public Double getCatSpedGiftedTalented () {
        return this.catSpedGiftedTalented;
    }

    public void setCatSpedGiftedTalented (Double catSpedGiftedTalented) {
        this.catSpedGiftedTalented = catSpedGiftedTalented;
    }

	@Column(name = "`AUDIT_ID`")
	private Integer auditId;

    public Integer getAuditId () {
        return this.auditId;
    }

    public void setAuditId (Integer auditId) {
        this.auditId = auditId;
    }

	@Column(name = "`TABOR_MILL`")
	private Double taborMill;

    public Double getTaborMill () {
        return this.taborMill;
    }

    public void setTaborMill (Double taborMill) {
        this.taborMill = taborMill;
    }

	@Column(name = "`SOT_ADJ_PERCENT`")
	private Double sotAdjPercent;

    public Double getSotAdjPercent () {
        return this.sotAdjPercent;
    }

    public void setSotAdjPercent (Double sotAdjPercent) {
        this.sotAdjPercent = sotAdjPercent;
    }

	@Column(name = "`FULL_FUNDING_MILL`")
	private Double fullFundingMill;

    public Double getFullFundingMill () {
        return this.fullFundingMill;
    }

    public void setFullFundingMill (Double fullFundingMill) {
        this.fullFundingMill = fullFundingMill;
    }

	@Column(name = "`STATE_EQUAL_ADJUST`")
	private Double stateEqualOwnerAdjust;

    public Double getStateEqualOwnerAdjust () {
        return this.stateEqualOwnerAdjust;
    }

    public void setStateEqualOwnerAdjust (Double stateEqualOwnerAdjust) {
        this.stateEqualOwnerAdjust = stateEqualOwnerAdjust;
    }

	@Column(name = "`STATE_AVERAGE_AT_RISK_PERCENT`")
	private Double stateAverageAtRiskPercent;

    public Double getStateAverageAtRiskPercent () {
        return this.stateAverageAtRiskPercent;
    }

    public void setStateAverageAtRiskPercent (Double stateAverageAtRiskPercent) {
        this.stateAverageAtRiskPercent = stateAverageAtRiskPercent;
    }

	@Column(name = "`MINIMUM_STATE_AID`")
	private Double minimumStateAid;

    public Double getMinimumStateAid () {
        return this.minimumStateAid;
    }

    public void setMinimumStateAid (Double minimumStateAid) {
        this.minimumStateAid = minimumStateAid;
    }

	@Column(name = "`BASE_PER_PUPIL_FUND`")
	private Double basePerPupilFund;

    public Double getBasePerPupilFund () {
        return this.basePerPupilFund;
    }

    public void setBasePerPupilFund (Double basePerPupilFund) {
        this.basePerPupilFund = basePerPupilFund;
    }

	@Column(name = "`AT_RISK_BASE_FACTOR`")
	private Double atRiskBaseFactor;

    public Double getAtRiskBaseFactor () {
        return this.atRiskBaseFactor;
    }

    public void setAtRiskBaseFactor (Double atRiskBaseFactor) {
        this.atRiskBaseFactor = atRiskBaseFactor;
    }

	@Column(name = "`ADJ_DISTRICT_TOTAL_PROGRAM`")
	private Double adjDistrictTotalProgram;

    public Double getAdjDistrictTotalProgram () {
        return this.adjDistrictTotalProgram;
    }

    public void setAdjDistrictTotalProgram (Double adjDistrictTotalProgram) {
        this.adjDistrictTotalProgram = adjDistrictTotalProgram;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`YTD_AUDIT_REPAY`")
	private Double ytdAuditRepay;

    public Double getYtdAuditRepay () {
        return this.ytdAuditRepay;
    }

    public void setYtdAuditRepay (Double ytdAuditRepay) {
        this.ytdAuditRepay = ytdAuditRepay;
    }

	@Column(name = "`MONTH_AUDIT_REPAY`")
	private Double monthAuditRepay;

    public Double getMonthAuditRepay () {
        return this.monthAuditRepay;
    }

    public void setMonthAuditRepay (Double monthAuditRepay) {
        this.monthAuditRepay = monthAuditRepay;
    }

	@Column(name = "`DISTRICT_CHARTER_FTE_COUNT`")
	private Double districtCharterFteCount;

    public Double getDistrictCharterFteCount () {
        return this.districtCharterFteCount;
    }

    public void setDistrictCharterFteCount (Double districtCharterFteCount) {
        this.districtCharterFteCount = districtCharterFteCount;
    }

	@Column(name = "`TOTAL_PROGRAM_CAT_BUYOUT`")
	private Double totalProgramCatBuyout;

    public Double getTotalProgramCatBuyout () {
        return this.totalProgramCatBuyout;
    }

    public void setTotalProgramCatBuyout (Double totalProgramCatBuyout) {
        this.totalProgramCatBuyout = totalProgramCatBuyout;
    }

	@Column(name = "`NEG_FACTOR`")
	private Double negFactor;

    public Double getNegFactor () {
        return this.negFactor;
    }

    public void setNegFactor (Double negFactor) {
        this.negFactor = negFactor;
    }

	@Column(name = "`CSI_ADMIN_YTD`")
	private Double csiAdminYtd;

    public Double getCsiAdminYtd () {
        return this.csiAdminYtd;
    }

    public void setCsiAdminYtd (Double csiAdminYtd) {
        this.csiAdminYtd = csiAdminYtd;
    }

	@Column(name = "`CSI_TOTAL_PROGRAM_FUND`")
	private Double csiTotalProgramFund;

    public Double getCsiTotalProgramFund () {
        return this.csiTotalProgramFund;
    }

    public void setCsiTotalProgramFund (Double csiTotalProgramFund) {
        this.csiTotalProgramFund = csiTotalProgramFund;
    }

	@Column(name = "`CHARTER_DEBT_YTD`")
	private Double charterDebtYtd;

    public Double getCharterDebtYtd () {
        return this.charterDebtYtd;
    }

    public void setCharterDebtYtd (Double charterDebtYtd) {
        this.charterDebtYtd = charterDebtYtd;
    }

	@Column(name = "`CHARTER_DEBT_MONTH`")
	private Double charterDebtMonth;

    public Double getCharterDebtMonth () {
        return this.charterDebtMonth;
    }

    public void setCharterDebtMonth (Double charterDebtMonth) {
        this.charterDebtMonth = charterDebtMonth;
    }

	@Column(name = "`CPP`")
	private Double cpp;

    public Double getCpp () {
        return this.cpp;
    }

    public void setCpp (Double cpp) {
        this.cpp = cpp;
    }

	@Column(name = "`SINGLE_DISTRICT_ONLINE_FTE`")
	private Double singleDistrictOnlineFte;

    public Double getSingleDistrictOnlineFte () {
        return this.singleDistrictOnlineFte;
    }

    public void setSingleDistrictOnlineFte (Double singleDistrictOnlineFte) {
        this.singleDistrictOnlineFte = singleDistrictOnlineFte;
    }

	@Column(name = "`MULTI_DISTRICT_ONLINE_FTE`")
	private Double multiDistrictOnlineFte;

    public Double getMultiDistrictOnlineFte () {
        return this.multiDistrictOnlineFte;
    }

    public void setMultiDistrictOnlineFte (Double multiDistrictOnlineFte) {
        this.multiDistrictOnlineFte = multiDistrictOnlineFte;
    }

	@Column(name = "`ESL_CSAP`")
	private Double eslCsap;

    public Double getEslCsap () {
        return this.eslCsap;
    }

    public void setEslCsap (Double eslCsap) {
        this.eslCsap = eslCsap;
    }

	@Column(name = "`SMALL_CENTER_PAYMENTS`")
	private Double smallCenterPayments;

    public Double getSmallCenterPayments () {
        return this.smallCenterPayments;
    }

    public void setSmallCenterPayments (Double smallCenterPayments) {
        this.smallCenterPayments = smallCenterPayments;
    }

	@Column(name = "`CHARTER_SCHOOL_FPC`")
	private Double charterSchoolFpc;

    public Double getCharterSchoolFpc () {
        return this.charterSchoolFpc;
    }

    public void setCharterSchoolFpc (Double charterSchoolFpc) {
        this.charterSchoolFpc = charterSchoolFpc;
    }

	@Column(name = "`FTE`")
	private Double fte;

    public Double getFte () {
        return this.fte;
    }

    public void setFte (Double fte) {
        this.fte = fte;
    }

	@Column(name = "`SOT_NET`")
	private Double sotNet;

    public Double getSotNet () {
        return this.sotNet;
    }

    public void setSotNet (Double sotNet) {
        this.sotNet = sotNet;
    }

	@Column(name = "`DISTRICT_CERT_TOTAL_ADD_FUND`")
	private Double districtCertTotalAddFund;

    public Double getDistrictCertTotalAddFund () {
        return this.districtCertTotalAddFund;
    }

    public void setDistrictCertTotalAddFund (Double districtCertTotalAddFund) {
        this.districtCertTotalAddFund = districtCertTotalAddFund;
    }

	@Column(name = "`MINIMUM_FORMULA_FUND`")
	private Double minimumFormulaFund;

    public Double getMinimumFormulaFund () {
        return this.minimumFormulaFund;
    }

    public void setMinimumFormulaFund (Double minimumFormulaFund) {
        this.minimumFormulaFund = minimumFormulaFund;
    }

	@Column(name = "`CSI_ADMIN_MONTH`")
	private Double csiAdminMonth;

    public Double getCsiAdminMonth () {
        return this.csiAdminMonth;
    }

    public void setCsiAdminMonth (Double csiAdminMonth) {
        this.csiAdminMonth = csiAdminMonth;
    }

	@Column(name = "`TOTAL_AT_RISK_FUNDING`")
	private Double totalAtRiskFunding;

    public Double getTotalAtRiskFunding () {
        return this.totalAtRiskFunding;
    }

    public void setTotalAtRiskFunding (Double totalAtRiskFunding) {
        this.totalAtRiskFunding = totalAtRiskFunding;
    }

	@Column(name = "`FORMULA_PUPIL_FUND`")
	private Double formulaPupilFund;

    public Double getFormulaPupilFund () {
        return this.formulaPupilFund;
    }

    public void setFormulaPupilFund (Double formulaPupilFund) {
        this.formulaPupilFund = formulaPupilFund;
    }

	@Column(name = "`FUNDED_AT_RISK_COUNT`")
	private Double fundedAtRiskCount;

    public Double getFundedAtRiskCount () {
        return this.fundedAtRiskCount;
    }

    public void setFundedAtRiskCount (Double fundedAtRiskCount) {
        this.fundedAtRiskCount = fundedAtRiskCount;
    }

	@Column(name = "`MEMBER_K_12`")
	private Double memberK12;

    public Double getMemberK12 () {
        return this.memberK12;
    }

    public void setMemberK12 (Double memberK12) {
        this.memberK12 = memberK12;
    }

	@Column(name = "`TOTAL_ADD_FUND`")
	private Double totalAddFund;

    public Double getTotalAddFund () {
        return this.totalAddFund;
    }

    public void setTotalAddFund (Double totalAddFund) {
        this.totalAddFund = totalAddFund;
    }

	@Column(name = "`TOTAL_MAX_FUND`")
	private Double totalMaxFund;

    public Double getTotalMaxFund () {
        return this.totalMaxFund;
    }

    public void setTotalMaxFund (Double totalMaxFund) {
        this.totalMaxFund = totalMaxFund;
    }

	@Column(name = "`TOTAL_FUND_INCLUDING_ONLINE`")
	private Double totalFundIncludingOnline;

    public Double getTotalFundIncludingOnline () {
        return this.totalFundIncludingOnline;
    }

    public void setTotalFundIncludingOnline (Double totalFundIncludingOnline) {
        this.totalFundIncludingOnline = totalFundIncludingOnline;
    }

	@Column(name = "`TOTAL_PROGRAM_TABOR`")
	private Double totalProgramTabor;

    public Double getTotalProgramTabor () {
        return this.totalProgramTabor;
    }

    public void setTotalProgramTabor (Double totalProgramTabor) {
        this.totalProgramTabor = totalProgramTabor;
    }

	@Column(name = "`CALC_CAT_BUY_MILL_LEVY`")
	private Double calcCatBuyMillLevy;

    public Double getCalcCatBuyMillLevy () {
        return this.calcCatBuyMillLevy;
    }

    public void setCalcCatBuyMillLevy (Double calcCatBuyMillLevy) {
        this.calcCatBuyMillLevy = calcCatBuyMillLevy;
    }

	@Column(name = "`CERT_CAT_BUY_MILL_LEVY`")
	private Double certCatBuyMillLevy;

    public Double getCertCatBuyMillLevy () {
        return this.certCatBuyMillLevy;
    }

    public void setCertCatBuyMillLevy (Double certCatBuyMillLevy) {
        this.certCatBuyMillLevy = certCatBuyMillLevy;
    }

	@Column(name = "`CAT_LEVY_ADJ`")
	private Double catLevyAdj;

    public Double getCatLevyAdj () {
        return this.catLevyAdj;
    }

    public void setCatLevyAdj (Double catLevyAdj) {
        this.catLevyAdj = catLevyAdj;
    }

	@Column(name = "`ALLOW_SPEND`")
	private Double allowSpend;

    public Double getAllowSpend () {
        return this.allowSpend;
    }

    public void setAllowSpend (Double allowSpend) {
        this.allowSpend = allowSpend;
    }

	@Column(name = "`YTD_SWAP`")
	private Double ytdSwap;

    public Double getYtdSwap () {
        return this.ytdSwap;
    }

    public void setYtdSwap (Double ytdSwap) {
        this.ytdSwap = ytdSwap;
    }

	@Column(name = "`ADJ_SWAP`")
	private Double adjSwap;

    public Double getAdjSwap () {
        return this.adjSwap;
    }

    public void setAdjSwap (Double adjSwap) {
        this.adjSwap = adjSwap;
    }

	@Column(name = "`YTD_PAYMENT`")
	private Double ytdPayment;

    public Double getYtdPayment () {
        return this.ytdPayment;
    }

    public void setYtdPayment (Double ytdPayment) {
        this.ytdPayment = ytdPayment;
    }

	@Column(name = "`ADJ_OODS`")
	private Double adjOods;

    public Double getAdjOods () {
        return this.adjOods;
    }

    public void setAdjOods (Double adjOods) {
        this.adjOods = adjOods;
    }

	@Column(name = "`YTD_OODS`")
	private Double ytdOods;

    public Double getYtdOods () {
        return this.ytdOods;
    }

    public void setYtdOods (Double ytdOods) {
        this.ytdOods = ytdOods;
    }

	@Column(name = "`ADJ_OTHER`")
	private Double adjOther;

    public Double getAdjOther () {
        return this.adjOther;
    }

    public void setAdjOther (Double adjOther) {
        this.adjOther = adjOther;
    }

	@Column(name = "`YTD_OTHER`")
	private Double ytdOther;

    public Double getYtdOther () {
        return this.ytdOther;
    }

    public void setYtdOther (Double ytdOther) {
        this.ytdOther = ytdOther;
    }

}