
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "AUDIT_TRACKING")
public class AuditTracking implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_TRACKING_SEQ", sequenceName="AUDIT_TRACKING_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_TRACKING_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
	@Column(name="ALERT")
	private String alert;
	@Column(name="AT_RISK_HOURS")
	private Double atRiskHours;
	@Column(name="AUDITOR_COMMENTS")
	private String auditorComments;
	@Column(name="AUDIT_CREATED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date auditCreated;
	@Column(name="AUDIT_COMPLETED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date auditCompleted;
	@Column(name="AUDIT_ID")
	private Integer auditID;
	@Column(name="AUDIT_STATUS")
	private String auditStatus;
	@Column(name="AUDIT_TYPE")
	private String auditType;
	@Column(name="BILLING_HOURS")
	private Double billingHours;
	@Column(name="DATA_MIGRATED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date dataMigrated;
	@Column(name="DOCUMENTS_RECEIVED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date documentsReceived;
	@Column(name="DRAFT_REPORT_COMPLETED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date draftReportCompleted;
	@Column(name="DRAFT_REPORT_ISSUED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date draftReportIssued;
	@Column(name="ELPA_HOURS")
	private Double elpaHours;
	@Column(name="FIELD_WORK_COMPLETED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date fieldWorkCompleted;
	@Column(name="FIELD_WORK_STARTED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date fieldWorkStarted;
	@Column(name="LEAD_AUDITOR")
	private String leadAuditor;
	@Column(name="ORGANIZATION_CODE")
	private String organizationCode;
	@Column(name="ORGANIZATION_ENGAGED")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date organizationEngaged;
	@Column(name="PROGRESS")
	private String progress;
	@Column(name="PUPIL_COUNT_HOURS")
	private Double pupilCountHours;
	@Column(name="REPORT_FINALIZED")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date reportFinalized;
	@Column(name="STATUS_DATE")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date statusDate;
	@Column(name="SUPERVISOR_COMMENTS")
	private String supervisorComments;
	@Column(name="SUPPORT_AUDITOR")
	private String supportAuditor;
	@Column(name="TOTAL_AUDIT_LIABILITY")
	private Double totalAuditLiability;
	@Column(name="TRANSPORTATION_HOURS")
	private Double transportationHours;
	
	@Column(name="UPDATE_TIMESTAMP")
        @Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date updateTimestamp;
	@Column(name="USER_ID")
	private String userId;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}
	public String getAlert() {
		return alert;
	}
	public void setAlert(String alert) {
		this.alert = alert;
	}
	public Double getAtRiskHours() {
		return atRiskHours;
	}
	public void setAtRiskHours(Double atRiskHours) {
		this.atRiskHours = atRiskHours;
	}
	public String getAuditorComments() {
		return auditorComments;
	}
	public void setAuditorComments(String auditorComments) {
		this.auditorComments = auditorComments;
	}
	public Date getAuditCreated() {
		return auditCreated;
	}
	public void setAuditCreated(Date auditCreated) {
		this.auditCreated = auditCreated;
	}
	public Date getAuditCompleted() {
		return auditCompleted;
	}
	public void setAuditCompleted(Date auditCompleted) {
		this.auditCompleted = auditCompleted;
	}
	public Integer getAuditID() {
		return auditID;
	}
	public void setAuditID(Integer auditID) {
		this.auditID = auditID;
	}
	public String getAuditStatus() {
		return auditStatus;
	}
	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}
	public String getAuditType() {
		return auditType;
	}
	public void setAuditType(String auditType) {
		this.auditType = auditType;
	}
	public Double getBillingHours() {
		return billingHours;
	}
	public void setBillingHours(Double billingHours) {
		this.billingHours = billingHours;
	}
	public Date getDataMigrated() {
		return dataMigrated;
	}
	public void setDataMigrated(Date dataMigrated) {
		this.dataMigrated = dataMigrated;
	}
	public Date getDocumentsReceived() {
		return documentsReceived;
	}
	public void setDocumentsReceived(Date documentsReceived) {
		this.documentsReceived = documentsReceived;
	}
	public Date getDraftReportCompleted() {
		return draftReportCompleted;
	}
	public void setDraftReportCompleted(Date draftReportCompleted) {
		this.draftReportCompleted = draftReportCompleted;
	}
	public Date getDraftReportIssued() {
		return draftReportIssued;
	}
	public void setDraftReportIssued(Date draftReportIssued) {
		this.draftReportIssued = draftReportIssued;
	}
	public Double getElpaHours() {
		return elpaHours;
	}
	public void setElpaHours(Double elpaHours) {
		this.elpaHours = elpaHours;
	}
	public Date getFieldWorkCompleted() {
		return fieldWorkCompleted;
	}
	public void setFieldWorkCompleted(Date fieldWorkCompleted) {
		this.fieldWorkCompleted = fieldWorkCompleted;
	}
	public Date getFieldWorkStarted() {
		return fieldWorkStarted;
	}
	public void setFieldWorkStarted(Date fieldWorkStarted) {
		this.fieldWorkStarted = fieldWorkStarted;
	}
	public String getLeadAuditor() {
		return leadAuditor;
	}
	public void setLeadAuditor(String leadAuditor) {
		this.leadAuditor = leadAuditor;
	}
	public String getOrganizationCode() {
		return organizationCode;
	}
	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}
	public Date getOrganizationEngaged() {
		return organizationEngaged;
	}
	public void setOrganizationEngaged(Date organizationEngaged) {
		this.organizationEngaged = organizationEngaged;
	}
	public String getProgress() {
		return progress;
	}
	public void setProgress(String progress) {
		this.progress = progress;
	}
	public Double getPupilCountHours() {
		return pupilCountHours;
	}
	public void setPupilCountHours(Double pupilCountHours) {
		this.pupilCountHours = pupilCountHours;
	}
	public Date getReportFinalized() {
		return reportFinalized;
	}
	public void setReportFinalized(Date reportFinalized) {
		this.reportFinalized = reportFinalized;
	}
	public Date getStatusDate() {
		return statusDate;
	}
	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}
	public String getSupervisorComments() {
		return supervisorComments;
	}
	public void setSupervisorComments(String supervisorComments) {
		this.supervisorComments = supervisorComments;
	}
	public String getSupportAuditor() {
		return supportAuditor;
	}
	public void setSupportAuditor(String supportAuditor) {
		this.supportAuditor = supportAuditor;
	}
	public Double getTotalAuditLiability() {
		return totalAuditLiability;
	}
	public void setTotalAuditLiability(Double totalAuditLiability) {
		this.totalAuditLiability = totalAuditLiability;
	}
	public Double getTransportationHours() {
		return transportationHours;
	}
	public void setTransportationHours(Double transportationHours) {
		this.transportationHours = transportationHours;
	}
	public Date getUpdateTimestamp() {
		return updateTimestamp;
	}
	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}	
	
}