
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDIT_TRAN`")
public class AuditTran implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_TRAN_SEQ", sequenceName="AUDIT_TRAN_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_TRAN_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`AUDIT_ID`")
	private Integer auditId;

    public Integer getAuditId () {
        return this.auditId;
    }

    public void setAuditId (Integer auditId) {
        this.auditId = auditId;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`TOTAL_MILES`")
	private Double totalMiles;

    public Double getTotalMiles () {
        return this.totalMiles;
    }

    public void setTotalMiles (Double totalMiles) {
        this.totalMiles = totalMiles;
    }

	@Column(name = "`ACT_MILES`")
	private Double actMiles;

    public Double getActMiles () {
        return this.actMiles;
    }

    public void setActMiles (Double actMiles) {
        this.actMiles = actMiles;
    }

	@Column(name = "`ADV_PAY`")
	private Double advPay;

    public Double getAdvPay () {
        return this.advPay;
    }

    public void setAdvPay (Double advPay) {
        this.advPay = advPay;
    }

	@Column(name = "`REIM_ADV_PAY`")
	private Double reimAdvPay;

    public Double getReimAdvPay () {
        return this.reimAdvPay;
    }

    public void setReimAdvPay (Double reimAdvPay) {
        this.reimAdvPay = reimAdvPay;
    }

	@Column(name = "`ADV_PAY_LY`")
	private Double advPayLy;

    public Double getAdvPayLy () {
        return this.advPayLy;
    }

    public void setAdvPayLy (Double advPayLy) {
        this.advPayLy = advPayLy;
    }

	@Column(name = "`REIM_TRAN_LY`")
	private Double reimTranLy;

    public Double getReimTranLy () {
        return this.reimTranLy;
    }

    public void setReimTranLy (Double reimTranLy) {
        this.reimTranLy = reimTranLy;
    }

	@Column(name = "`REIM_TRAN`")
	private Double reimTran;

    public Double getReimTran () {
        return this.reimTran;
    }

    public void setReimTran (Double reimTran) {
        this.reimTran = reimTran;
    }

	@Column(name = "`DESEG_REIM`")
	private Double desegReim;

    public Double getDesegReim () {
        return this.desegReim;
    }

    public void setDesegReim (Double desegReim) {
        this.desegReim = desegReim;
    }

	@Column(name = "`EX_REIM`")
	private Double exReim;

    public Double getExReim () {
        return this.exReim;
    }

    public void setExReim (Double exReim) {
        this.exReim = exReim;
    }

	@Column(name = "`BOARD_TRAN`")
	private Long boardTran;

    public Long getBoardTran () {
        return this.boardTran;
    }

    public void setBoardTran (Long boardTran) {
        this.boardTran = boardTran;
    }

	@Column(name = "`REG_MILES`")
	private Long regMiles;

    public Long getRegMiles () {
        return this.regMiles;
    }

    public void setRegMiles (Long regMiles) {
        this.regMiles = regMiles;
    }

	@Column(name = "`SCHOOL_DAYS`")
	private Long schoolDays;

    public Long getSchoolDays () {
        return this.schoolDays;
    }

    public void setSchoolDays (Long schoolDays) {
        this.schoolDays = schoolDays;
    }

	@Column(name = "`PUPIL_TRAN`")
	private Long pupilTran;

    public Long getPupilTran () {
        return this.pupilTran;
    }

    public void setPupilTran (Long pupilTran) {
        this.pupilTran = pupilTran;
    }

	@Column(name = "`OPER_TRAN`")
	private Double operTran;

    public Double getOperTran () {
        return this.operTran;
    }

    public void setOperTran (Double operTran) {
        this.operTran = operTran;
    }

	@Column(name = "`IND_CONT`")
	private Long indCont;

    public Long getIndCont () {
        return this.indCont;
    }

    public void setIndCont (Long indCont) {
        this.indCont = indCont;
    }

	@Column(name = "`CAP_OUT_TRAN`")
	private Double capOutTran;

    public Double getCapOutTran () {
        return this.capOutTran;
    }

    public void setCapOutTran (Double capOutTran) {
        this.capOutTran = capOutTran;
    }

	@Column(name = "`MIG_MILES`")
	private Double migMiles;

    public Double getMigMiles () {
        return this.migMiles;
    }

    public void setMigMiles (Double migMiles) {
        this.migMiles = migMiles;
    }

	@Column(name = "`REG_D_MILES`")
	private Double regDMiles;

    public Double getRegDMiles () {
        return this.regDMiles;
    }

    public void setRegDMiles (Double regDMiles) {
        this.regDMiles = regDMiles;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`DATE_CHANGED`")
	private String dateChanged;

    public String getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (String dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

}