
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`ORGANIZATION`")
public class Organization implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`USER_ID`")
	private String userId;

    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

	@Column(name = "`UPDATE_TIMESTAMP`")
	private Date updateTimestamp;

    public Date getUpdateTimestamp () {
        return this.updateTimestamp;
    }

    public void setUpdateTimestamp (Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

	@Column(name = "`DATE_CLOSED`")
	private Date dateClosed;

    public Date getDateClosed () {
        return this.dateClosed;
    }

    public void setDateClosed (Date dateClosed) {
        this.dateClosed = dateClosed;
    }

	@Column(name = "`DATE_OPENED`")
	private Date dateOpened;

    public Date getDateOpened () {
        return this.dateOpened;
    }

    public void setDateOpened (Date dateOpened) {
        this.dateOpened = dateOpened;
    }

	@Column(name = "`AUDITOR_COMMENT`")
	private String auditorComment;

    public String getAuditorComment () {
        return this.auditorComment;
    }

    public void setAuditorComment (String auditorComment) {
        this.auditorComment = auditorComment;
    }

	@Column(name = "`AUDIT_FREQUENCY`")
	private String auditFrequency;

    public String getAuditFrequency () {
        return this.auditFrequency;
    }

    public void setAuditFrequency (String auditFrequency) {
        this.auditFrequency = auditFrequency;
    }

	@Column(name = "`ORGANIZATION_SIZE`")
	private String organizationSize;

    public String getOrganizationSize () {
        return this.organizationSize;
    }

    public void setOrganizationSize (String organizationSize) {
        this.organizationSize = organizationSize;
    }

	@Column(name = "`REGION`")
	private String region;

    public String getRegion () {
        return this.region;
    }

    public void setRegion (String region) {
        this.region = region;
    }

	@Column(name = "`COUNTY_NAME`")
	private String countyName;

    public String getCountyName () {
        return this.countyName;
    }

    public void setCountyName (String countyName) {
        this.countyName = countyName;
    }

	@Column(name = "`COUNTY_CODE`")
	private String countyCode;

    public String getCountyCode () {
        return this.countyCode;
    }

    public void setCountyCode (String countyCode) {
        this.countyCode = countyCode;
    }

	@Column(name = "`ORGANIZATION_CODE`")
	private String organizationCode;

    public String getOrganizationCode () {
        return this.organizationCode;
    }

    public void setOrganizationCode (String organizationCode) {
        this.organizationCode = organizationCode;
    }

}