/*
 * Copyright ResQSoft, Inc. 2011
 */
package com.cdoe.biz.model.audit;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDITOR_ROLE`")
public class AuditorRole implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@SequenceGenerator(name="AUDIT_HOURS_SEQ", sequenceName="AUDIT_HOURS_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="AUDIT_HOURS_SEQ")
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`USER_ID`")
	private String userId;

    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

	@Column(name = "`UPDATE_TIMESTAMP`")
	private Date updateTimestamp;

    public Date getUpdateTimestamp () {
        return this.updateTimestamp;
    }

    public void setUpdateTimestamp (Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

	@Column(name = "`EMPLOYED_DATE`")
	private Date employedDate;

    public Date getEmployedDate () {
        return this.employedDate;
    }

    public void setEmployedDate (Date employedDate) {
        this.employedDate = employedDate;
    }

	@Column(name = "`AUDITOR_ID`")
	private Integer auditorId;

    public Integer getAuditorId () {
        return this.auditorId;
    }

    public void setAuditorId (Integer auditorId) {
        this.auditorId = auditorId;
    }

	@Column(name = "`END_DATE`")
	private Date endDate;

    public Date getEndDate () {
        return this.endDate;
    }

    public void setEndDate (Date endDate) {
        this.endDate = endDate;
    }

	@Column(name = "`AUDIT_ROLE`")
	private String auditRole;

    public String getAuditRole () {
        return this.auditRole;
    }

    public void setAuditRole (String auditRole) {
        this.auditRole = auditRole;
    }

	@Column(name = "`AUDITOR_NAME`")
	private String auditorName;

    public String getAuditorName () {
        return this.auditorName;
    }

    public void setAuditorName (String auditorName) {
        this.auditorName = auditorName;
    }

}